/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000B90(spu_context* ctx) {
        ctx->gpr[35] = spu_ceqi(ctx->gpr[3], 0);
        ctx->gpr[6] = spu_ls_read128(ctx, 0xAD0);
        ctx->gpr[7] = spu_ceqi(ctx->gpr[3], 1);
        ctx->gpr[25] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[34] = spu_sfi(ctx->gpr[35], 0);
        ctx->gpr[49] = spu_cwd(ctx->gpr[1], 4);
        ctx->gpr[42] = spu_il(128);
        ctx->gpr[29] = spu_fsmbi(0x0);
        ctx->gpr[40] = spu_sfi(ctx->gpr[7], 0);
        ctx->gpr[44] = spu_fsmbi(0x0);
        ctx->gpr[48] = spu_il(208);
        ctx->gpr[22] = spu_rotqbyi(ctx->gpr[6], 12);
        ctx->gpr[45] = spu_il(1);
        ctx->gpr[46] = spu_ila(0x8000);
        ctx->gpr[47] = spu_ilhu(0x8000);
        ctx->gpr[5] = spu_ceqi(ctx->gpr[22], 32);
        ctx->gpr[37] = spu_clgti(ctx->gpr[22], 15);
        ctx->gpr[39] = spu_cbx(ctx->gpr[1], ctx->gpr[22]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[5], 0);
        ctx->gpr[38] = spu_clgti(ctx->gpr[22], 31);
        ctx->gpr[3] = spu_or(ctx->gpr[34], ctx->gpr[4]);
        ctx->gpr[41] = spu_ilh(0x404);
        ctx->gpr[2] = spu_ceqbi(ctx->gpr[3], 0);
        ctx->gpr[43] = spu_il(180);
        ctx->gpr[36] = spu_xsbh(ctx->gpr[2]);
        ctx->gpr[33] = spu_ila(0x100);
        { ctx->pc = 0xBF8; spu_func_00000BF8(ctx); return; }
}

void spu_func_00000BF8(spu_context* ctx) {
        ctx->gpr[53] = spu_ls_read128(ctx, 0xAC0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[33]);
        ctx->gpr[51] = spu_shlqbyi(ctx->gpr[53], 4);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[53]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[51]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[42]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[29]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[48]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdAtomicStat);
        /* sync */;
        ctx->gpr[50] = spu_ls_read128(ctx, 0xAC0);
        ctx->gpr[23] = spu_ls_read128(ctx, 0xA70);
        ctx->gpr[27] = spu_il(15);
        ctx->gpr[20] = spu_ls_read128(ctx, 0xA30);
        ctx->gpr[32] = spu_ceqi(ctx->gpr[38], 0);
        ctx->gpr[21] = spu_ls_read128(ctx, 0xA90);
        ctx->gpr[26] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[30] = spu_ls_read128(ctx, 0xA20);
        ctx->gpr[28] = spu_andi(ctx->gpr[32], -16);
        ctx->gpr[31] = spu_ls_read128(ctx, 0xA80);
        ctx->gpr[16] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[18] = spu_rotqbyi(ctx->gpr[50], 8);
        ctx->gpr[26] = spu_shufb(ctx->gpr[28], ctx->gpr[27], ctx->gpr[19]);
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[23], 15);
        ctx->gpr[8] = spu_fsm(ctx->gpr[16]);
        ctx->gpr[39] = spu_selb(ctx->gpr[19], ctx->gpr[29], ctx->gpr[17]);
        ctx->gpr[24] = spu_sf(ctx->gpr[21], ctx->gpr[20]);
        ctx->gpr[13] = spu_shl(ctx->gpr[45], ctx->gpr[18]);
        ctx->gpr[12] = spu_sf(ctx->gpr[31], ctx->gpr[30]);
        ctx->gpr[14] = spu_andi(ctx->gpr[9], 255);
        ctx->gpr[15] = spu_andc(ctx->gpr[24], ctx->gpr[17]);
        ctx->gpr[32] = spu_shlqbyi(ctx->gpr[12], 0);
        ctx->gpr[4] = spu_and(ctx->gpr[14], ctx->gpr[13]);
        ctx->gpr[11] = spu_a(ctx->gpr[12], ctx->gpr[15]);
        ctx->gpr[8] = spu_shufb(ctx->gpr[11], ctx->gpr[12], ctx->gpr[14]);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = 0xEC8; spu_func_00000EC8(ctx); return; }
        ctx->gpr[64] = spu_il(0);
        ctx->gpr[75] = spu_ls_read128(ctx, 0xA70);
        ctx->gpr[61] = spu_il(0);
        ctx->gpr[12] = spu_ls_read128(ctx, 0xA60);
        ctx->gpr[60] = spu_andbi(ctx->gpr[14], -16);
        ctx->gpr[67] = spu_ls_read128(ctx, 0xAE0);
        ctx->gpr[51] = spu_andbi(ctx->gpr[14], 15);
        ctx->gpr[59] = spu_ls_read128(ctx, 0xAD0);
        ctx->gpr[21] = spu_rotmi(ctx->gpr[60], 124);
        ctx->gpr[55] = spu_ls_read128(ctx, 0xA50);
        ctx->gpr[7] = spu_ls_read128(ctx, 0xAA0);
        ctx->gpr[27] = spu_rotqbyi(ctx->gpr[75], 4);
        ctx->gpr[69] = spu_rotqbyi(ctx->gpr[12], 12);
        ctx->gpr[54] = spu_rotqbyi(ctx->gpr[67], 12);
        ctx->gpr[58] = spu_ori(ctx->gpr[67], 0);
        ctx->gpr[57] = spu_rotqbyi(ctx->gpr[59], 12);
        ctx->gpr[74] = spu_andi(ctx->gpr[27], 255);
        ctx->gpr[23] = spu_rotqbyi(ctx->gpr[75], 14);
        ctx->gpr[65] = spu_ceqi(ctx->gpr[69], 0);
        ctx->gpr[26] = spu_rotqbyi(ctx->gpr[75], 6);
        ctx->gpr[73] = spu_sfi(ctx->gpr[74], 0);
        ctx->gpr[9] = spu_ls_read128(ctx, 0xA00);
        ctx->gpr[71] = spu_sfi(ctx->gpr[74], 0);
        ctx->gpr[62] = spu_shlqbyi(ctx->gpr[65], 0);
        ctx->gpr[66] = spu_rotm(ctx->gpr[46], ctx->gpr[73]);
        ctx->gpr[6] = spu_ls_read128(ctx, 0xA10);
        ctx->gpr[63] = spu_rotm(ctx->gpr[47], ctx->gpr[71]);
        ctx->gpr[68] = spu_fsmb(ctx->gpr[23]);
        ctx->gpr[30] = spu_rotmi(ctx->gpr[54], 112);
        ctx->gpr[79] = spu_fsmb(ctx->gpr[54]);
        ctx->gpr[31] = spu_andbi(ctx->gpr[55], -16);
        ctx->gpr[28] = spu_shlqbyi(ctx->gpr[69], 0);
        ctx->gpr[65] = spu_shufb(ctx->gpr[64], ctx->gpr[66], ctx->gpr[19]);
        ctx->gpr[65] = spu_fsmb(ctx->gpr[26]);
        ctx->gpr[62] = spu_shufb(ctx->gpr[61], ctx->gpr[63], ctx->gpr[18]);
        ctx->gpr[60] = spu_cbd(ctx->gpr[1], 11);
        ctx->gpr[5] = spu_andbi(ctx->gpr[7], 15);
        ctx->gpr[67] = spu_fsmb(ctx->gpr[19]);
        ctx->gpr[4] = spu_rotmi(ctx->gpr[31], 124);
        ctx->gpr[64] = spu_fsmb(ctx->gpr[18]);
        ctx->gpr[53] = spu_sfi(ctx->gpr[57], 0);
        ctx->gpr[20] = spu_fsmb(ctx->gpr[30]);
        ctx->gpr[56] = spu_sfi(ctx->gpr[57], 0);
        ctx->gpr[30] = spu_ila(0x8000);
        ctx->gpr[31] = spu_ilhu(0x8000);
        ctx->gpr[73] = spu_roti(ctx->gpr[5], 4);
        ctx->gpr[17] = spu_rotm(ctx->gpr[31], ctx->gpr[53]);
        ctx->gpr[8] = spu_rotm(ctx->gpr[30], ctx->gpr[56]);
        ctx->gpr[52] = spu_or(ctx->gpr[68], ctx->gpr[67]);
        ctx->gpr[14] = spu_or(ctx->gpr[65], ctx->gpr[64]);
        ctx->gpr[54] = spu_clgtb(ctx->gpr[9], ctx->gpr[51]);
        ctx->gpr[72] = spu_fsmb(ctx->gpr[17]);
        ctx->gpr[71] = spu_andbi(ctx->gpr[7], -16);
        ctx->gpr[74] = spu_fsmb(ctx->gpr[8]);
        ctx->gpr[53] = spu_clgtb(ctx->gpr[6], ctx->gpr[21]);
        ctx->gpr[50] = spu_andbi(ctx->gpr[55], 15);
        ctx->gpr[10] = spu_or(ctx->gpr[52], ctx->gpr[54]);
        ctx->gpr[15] = spu_clgtb(ctx->gpr[50], ctx->gpr[51]);
        ctx->gpr[77] = spu_clgtb(ctx->gpr[4], ctx->gpr[21]);
        ctx->gpr[78] = spu_or(ctx->gpr[14], ctx->gpr[53]);
        ctx->gpr[2] = spu_clgtbi(ctx->gpr[73], 0);
        ctx->gpr[3] = spu_clgtbi(ctx->gpr[71], 0);
        ctx->gpr[76] = spu_and(ctx->gpr[15], ctx->gpr[10]);
        ctx->gpr[75] = spu_and(ctx->gpr[77], ctx->gpr[78]);
        ctx->gpr[11] = spu_and(ctx->gpr[20], ctx->gpr[2]);
        ctx->gpr[12] = spu_and(ctx->gpr[79], ctx->gpr[3]);
        ctx->gpr[41] = spu_shufb(ctx->gpr[71], ctx->gpr[72], ctx->gpr[69]);
        ctx->gpr[14] = spu_and(ctx->gpr[11], ctx->gpr[76]);
        ctx->gpr[10] = spu_and(ctx->gpr[12], ctx->gpr[75]);
        ctx->gpr[41] = spu_shufb(ctx->gpr[73], ctx->gpr[74], ctx->gpr[70]);
        ctx->gpr[7] = spu_and(ctx->gpr[69], ctx->gpr[10]);
        ctx->gpr[8] = spu_and(ctx->gpr[70], ctx->gpr[14]);
        ctx->gpr[59] = spu_andbi(ctx->gpr[65], 2);
        ctx->gpr[66] = spu_clgtb(ctx->gpr[7], ctx->gpr[8]);
        ctx->gpr[62] = spu_andbi(ctx->gpr[68], 2);
        ctx->gpr[66] = spu_shufb(ctx->gpr[8], ctx->gpr[7], ctx->gpr[55]);
        ctx->gpr[63] = spu_andbi(ctx->gpr[67], 4);
        ctx->gpr[57] = spu_rotqbyi(ctx->gpr[55], 8);
        ctx->gpr[61] = spu_andbi(ctx->gpr[64], 4);
        ctx->gpr[52] = spu_or(ctx->gpr[62], ctx->gpr[63]);
        ctx->gpr[51] = spu_or(ctx->gpr[59], ctx->gpr[61]);
        ctx->gpr[56] = spu_clgtb(ctx->gpr[57], ctx->gpr[55]);
        ctx->gpr[9] = spu_andhi(ctx->gpr[54], 257);
        ctx->gpr[56] = spu_shufb(ctx->gpr[55], ctx->gpr[57], ctx->gpr[21]);
        ctx->gpr[6] = spu_andhi(ctx->gpr[53], 257);
        ctx->gpr[50] = spu_rotqbyi(ctx->gpr[21], 4);
        ctx->gpr[71] = spu_or(ctx->gpr[9], ctx->gpr[52]);
        ctx->gpr[69] = spu_or(ctx->gpr[6], ctx->gpr[51]);
        ctx->gpr[18] = spu_clgtb(ctx->gpr[50], ctx->gpr[21]);
        ctx->gpr[18] = spu_shufb(ctx->gpr[21], ctx->gpr[50], ctx->gpr[17]);
        ctx->gpr[20] = spu_rotqbyi(ctx->gpr[17], 2);
        ctx->gpr[19] = spu_clgtb(ctx->gpr[20], ctx->gpr[17]);
        ctx->gpr[19] = spu_shufb(ctx->gpr[17], ctx->gpr[20], ctx->gpr[13]);
        ctx->gpr[16] = spu_rotqbyi(ctx->gpr[13], 1);
        ctx->gpr[15] = spu_clgtb(ctx->gpr[16], ctx->gpr[13]);
        ctx->gpr[15] = spu_shufb(ctx->gpr[13], ctx->gpr[16], ctx->gpr[3]);
        ctx->gpr[5] = spu_ceqb(ctx->gpr[8], ctx->gpr[3]);
        ctx->gpr[4] = spu_ceqb(ctx->gpr[7], ctx->gpr[3]);
        ctx->gpr[2] = spu_and(ctx->gpr[5], ctx->gpr[14]);
        ctx->gpr[79] = spu_and(ctx->gpr[4], ctx->gpr[10]);
        /* TODO spu: gbb $r78, $r2, $r0 */;
        /* TODO spu: gbb $r77, $r79, $r0 */;
        ctx->gpr[76] = spu_shli(ctx->gpr[78], 16);
        ctx->gpr[75] = spu_or(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[65] = spu_clz(ctx->gpr[75]);
        ctx->gpr[73] = spu_clgti(ctx->gpr[65], 15);
        ctx->gpr[68] = spu_ai(ctx->gpr[65], -3);
        ctx->gpr[72] = spu_ceqi(ctx->gpr[73], 0);
        ctx->gpr[70] = spu_fsm(ctx->gpr[72]);
        ctx->gpr[70] = spu_shufb(ctx->gpr[69], ctx->gpr[71], ctx->gpr[67]);
        ctx->gpr[66] = spu_rotqby(ctx->gpr[67], ctx->gpr[68]);
        ctx->gpr[64] = spu_andi(ctx->gpr[66], 255);
        ctx->gpr[49] = spu_selb(ctx->gpr[64], ctx->gpr[65], ctx->gpr[18]);
        ctx->gpr[63] = spu_ceq(ctx->gpr[22], ctx->gpr[18]);
        ctx->gpr[62] = spu_ceqi(ctx->gpr[18], 32);
        ctx->gpr[8] = spu_shlqbyi(ctx->gpr[18], 0);
        ctx->gpr[61] = spu_sfi(ctx->gpr[63], 0);
        ctx->gpr[59] = spu_sfi(ctx->gpr[62], 0);
        ctx->gpr[57] = spu_or(ctx->gpr[34], ctx->gpr[61]);
        ctx->gpr[60] = spu_selb(ctx->gpr[59], ctx->gpr[58], ctx->gpr[55]);
        ctx->gpr[56] = spu_ceqbi(ctx->gpr[57], 0);
        ctx->gpr[54] = spu_xsbh(ctx->gpr[56]);
        spu_ls_write128(ctx, 0xAE0, ctx->gpr[55]);
        if (ctx->gpr[54]._u16[1] != 0) { ctx->pc = 0xFB8; spu_func_00000FB8(ctx); return; }
        ctx->gpr[2] = spu_sfi(ctx->gpr[18], 0);
        ctx->gpr[78] = spu_ls_read128(ctx, 0xA70);
        ctx->gpr[20] = spu_sfi(ctx->gpr[18], 0);
        ctx->gpr[15] = spu_chd(ctx->gpr[1], 0);
        ctx->gpr[3] = spu_rotm(ctx->gpr[30], ctx->gpr[2]);
        ctx->gpr[76] = spu_chd(ctx->gpr[1], 8);
        ctx->gpr[10] = spu_rotm(ctx->gpr[31], ctx->gpr[20]);
        ctx->gpr[77] = spu_andi(ctx->gpr[27], 255);
        ctx->gpr[79] = spu_andc(ctx->gpr[23], ctx->gpr[3]);
        ctx->gpr[58] = spu_andc(ctx->gpr[26], ctx->gpr[10]);
        ctx->gpr[4] = spu_ceq(ctx->gpr[18], ctx->gpr[77]);
        ctx->gpr[15] = spu_selb(ctx->gpr[79], ctx->gpr[78], ctx->gpr[11]);
        ctx->gpr[76] = spu_selb(ctx->gpr[58], ctx->gpr[11], ctx->gpr[2]);
        { ctx->pc = 0xEAC; spu_func_00000EAC(ctx); return; }
}

void spu_func_00000EAC(spu_context* ctx) {
        ctx->gpr[21] = spu_ls_read128(ctx, 0xA60);
        ctx->gpr[4] = spu_or(ctx->gpr[28], ctx->gpr[4]);
        ctx->gpr[50] = spu_cwd(ctx->gpr[1], 12);
        spu_ls_write128(ctx, 0xA70, ctx->gpr[2]);
        ctx->gpr[50] = spu_selb(ctx->gpr[4], ctx->gpr[21], ctx->gpr[14]);
        spu_ls_write128(ctx, 0xA60, ctx->gpr[14]);
        { ctx->pc = 0xF04; spu_func_00000F04(ctx); return; }
}

void spu_func_00000EC8(spu_context* ctx) {
        ctx->gpr[8] = spu_il(32);
        ctx->gpr[52] = spu_ls_read128(ctx, 0xAE0);
        ctx->gpr[55] = spu_cbd(ctx->gpr[1], 11);
        ctx->gpr[56] = spu_fsmbi(0x1000);
        ctx->gpr[18] = spu_andbi(ctx->gpr[56], 32);
        ctx->gpr[55] = spu_selb(ctx->gpr[44], ctx->gpr[52], ctx->gpr[51]);
        spu_ls_write128(ctx, 0xAE0, ctx->gpr[51]);
        if (ctx->gpr[36]._u16[1] != 0) { ctx->pc = 0xF04; spu_func_00000F04(ctx); return; }
        ctx->gpr[7] = spu_andc(ctx->gpr[9], ctx->gpr[4]);
        ctx->gpr[5] = spu_ls_read128(ctx, 0xA70);
        ctx->gpr[17] = spu_cbd(ctx->gpr[1], 2);
        ctx->gpr[6] = spu_fsmbi(0x1000);
        ctx->gpr[18] = spu_andbi(ctx->gpr[6], 32);
        ctx->gpr[17] = spu_selb(ctx->gpr[7], ctx->gpr[5], ctx->gpr[57]);
        spu_ls_write128(ctx, 0xA70, ctx->gpr[57]);
        { ctx->pc = 0xF04; spu_func_00000F04(ctx); return; }
}

void spu_func_00000F04(spu_context* ctx) {
        ctx->gpr[69] = spu_ceq(ctx->gpr[8], ctx->gpr[22]);
        ctx->gpr[68] = spu_clgti(ctx->gpr[8], 31);
        ctx->gpr[63] = spu_cbx(ctx->gpr[1], ctx->gpr[8]);
        ctx->gpr[26] = spu_nor(ctx->gpr[69], ctx->gpr[69]);
        ctx->gpr[19] = spu_ls_read128(ctx, 0xA20);
        ctx->gpr[67] = spu_ceqi(ctx->gpr[68], 0);
        ctx->gpr[16] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[66] = spu_sfi(ctx->gpr[26], 0);
        ctx->gpr[65] = spu_andi(ctx->gpr[67], 16);
        ctx->gpr[64] = spu_ceqi(ctx->gpr[16], 0);
        ctx->gpr[9] = spu_il(1);
        ctx->gpr[13] = spu_and(ctx->gpr[40], ctx->gpr[66]);
        ctx->gpr[64] = spu_shufb(ctx->gpr[65], ctx->gpr[9], ctx->gpr[62]);
        ctx->gpr[9] = spu_sfi(ctx->gpr[35], 0);
        ctx->gpr[63] = spu_selb(ctx->gpr[62], ctx->gpr[29], ctx->gpr[5]);
        ctx->gpr[61] = spu_ceqi(ctx->gpr[13], 0);
        ctx->gpr[59] = spu_ceqi(ctx->gpr[9], 0);
        ctx->gpr[6] = spu_fsm(ctx->gpr[61]);
        ctx->gpr[7] = spu_fsm(ctx->gpr[59]);
        ctx->gpr[54] = spu_a(ctx->gpr[32], ctx->gpr[5]);
        ctx->gpr[60] = spu_a(ctx->gpr[24], ctx->gpr[5]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[54], ctx->gpr[19], ctx->gpr[28]);
        ctx->gpr[6] = spu_shufb(ctx->gpr[60], ctx->gpr[24], ctx->gpr[31]);
        spu_ls_write128(ctx, 0xA20, ctx->gpr[28]);
        spu_ls_write128(ctx, 0xA30, ctx->gpr[31]);
        /* sync */;
        ctx->gpr[30] = spu_ls_read128(ctx, 0xAC0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[33]);
        ctx->gpr[32] = spu_shlqbyi(ctx->gpr[30], 4);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[30]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[32]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[42]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[29]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[43]);
        ctx->gpr[24] = spu_rdch(ctx, MFC_RdAtomicStat);
        if (ctx->gpr[24]._u32[0] != 0) { ctx->pc = 0xBF8; spu_func_00000BF8(ctx); return; }
        ctx->gpr[29] = spu_ls_read128(ctx, 0xA80);
        ctx->gpr[35] = spu_il(0);
        ctx->gpr[6] = spu_shufb(ctx->gpr[5], ctx->gpr[35], ctx->gpr[34]);
        spu_ls_write128(ctx, 0xA90, ctx->gpr[34]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[5], ctx->gpr[29], ctx->gpr[25]);
        spu_ls_write128(ctx, 0xA80, ctx->gpr[25]);
        if (ctx->gpr[9]._u32[0] != 0) { ctx->pc = 0xFCC; spu_func_00000FCC(ctx); return; }
        ctx->gpr[8] = spu_ori(ctx->gpr[22], 0);
        { ctx->pc = 0xFCC; spu_func_00000FCC(ctx); return; }
}

void spu_func_00000FB8(spu_context* ctx) {
        ctx->gpr[4] = spu_il(0);
        ctx->gpr[71] = spu_ls_read128(ctx, 0xA70);
        ctx->gpr[72] = spu_chd(ctx->gpr[1], 0);
        ctx->gpr[72] = spu_selb(ctx->gpr[23], ctx->gpr[71], ctx->gpr[2]);
        { ctx->pc = 0xEAC; spu_func_00000EAC(ctx); return; }
}

void spu_func_00000FCC(spu_context* ctx) {
        ctx->gpr[37] = spu_ls_read128(ctx, 0xAD0);
        ctx->gpr[3] = spu_ori(ctx->gpr[18], 0);
        ctx->gpr[38] = spu_cwd(ctx->gpr[1], 12);
        ctx->gpr[38] = spu_selb(ctx->gpr[8], ctx->gpr[37], ctx->gpr[36]);
        spu_ls_write128(ctx, 0xAD0, ctx->gpr[36]);
        return;
}

void spu_func_00000FE8(spu_context* ctx) {
        ctx->gpr[35] = spu_andi(ctx->gpr[3], 15);
        ctx->gpr[36] = spu_fsmbi(0x202);
        ctx->gpr[32] = spu_clgti(ctx->gpr[3], 31);
        ctx->gpr[17] = spu_ls_read128(ctx, 0xAC0);
        ctx->gpr[33] = spu_shli(ctx->gpr[35], 5);
        ctx->gpr[8] = spu_ls_read128(ctx, 0x1180);
        ctx->gpr[34] = spu_il(4096);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[28] = spu_clgti(ctx->gpr[3], 15);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[27] = spu_ceqi(ctx->gpr[32], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[1]);
        ctx->gpr[29] = spu_a(ctx->gpr[33], ctx->gpr[34]);
        ctx->gpr[11] = spu_rotqbyi(ctx->gpr[3], 4);
        ctx->gpr[31] = spu_il(2816);
        ctx->gpr[21] = spu_fsm(ctx->gpr[27]);
        ctx->gpr[25] = spu_ceqi(ctx->gpr[28], 0);
        ctx->gpr[22] = spu_rotqmbyi(ctx->gpr[29], 124);
        ctx->gpr[26] = spu_a(ctx->gpr[33], ctx->gpr[31]);
        spu_ls_write128(ctx, 0x3FF40, ctx->gpr[9]);
        ctx->gpr[23] = spu_andbi(ctx->gpr[36], 13);
        ctx->gpr[10] = spu_fsm(ctx->gpr[25]);
        ctx->gpr[24] = spu_ila(0x3FFE0);
        ctx->gpr[18] = spu_rotqmbyi(ctx->gpr[26], 124);
        ctx->gpr[21] = spu_shufb(ctx->gpr[23], ctx->gpr[22], ctx->gpr[19]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[24]);
        ctx->gpr[12] = spu_il(32);
        ctx->gpr[10] = spu_shufb(ctx->gpr[19], ctx->gpr[18], ctx->gpr[16]);
        ctx->gpr[20] = spu_ila(0x3FFD0);
        ctx->gpr[7] = spu_cg(ctx->gpr[16], ctx->gpr[17]);
        ctx->gpr[10] = spu_il(31);
        spu_ls_write128(ctx, 0x3FEC0, ctx->gpr[20]);
        ctx->gpr[9] = spu_ilhu(0x8000);
        ctx->gpr[8] = spu_selb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[15]);
        ctx->gpr[7] = spu_il(64);
        ctx->gpr[8] = spu_il(2);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -32);
        ctx->gpr[15] = spu_addx(ctx->gpr[16], ctx->gpr[17], ctx->gpr[15]);
        ctx->gpr[1] = spu_ila(0x3FFB0);
        ctx->gpr[13] = spu_shlqbyi(ctx->gpr[15], 4);
        ctx->gpr[14] = spu_ori(ctx->gpr[15], 0);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[14]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[13]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[12]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[10]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[7]);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[9]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[8]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[4] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[6] = spu_ls_read128(ctx, 0xAD0);
        ctx->gpr[5] = spu_ceq(ctx->gpr[6], ctx->gpr[4]);
        ctx->gpr[3] = spu_gb(ctx->gpr[5]);
        ctx->gpr[2] = spu_cgti(ctx->gpr[3], 11);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x1120; spu_func_00001120(ctx); return; }
        ctx->gpr[46] = spu_ls_read128(ctx, 0x3FFC0);
        ctx->gpr[49] = spu_il(2560);
        ctx->gpr[47] = spu_shlqbyi(ctx->gpr[4], 4);
        ctx->gpr[43] = spu_cwd(ctx->gpr[1], 8);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[49]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[4]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[47]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[46]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[10]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[7]);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[9]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[8]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[40] = spu_cdd(ctx->gpr[1], 0);
        ctx->gpr[45] = spu_ls_read128(ctx, 0x3FFC0);
        ctx->gpr[41] = spu_ls_read128(ctx, 0xAD0);
        ctx->gpr[38] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[44] = spu_rotqbyi(ctx->gpr[45], 1);
        ctx->gpr[42] = spu_andi(ctx->gpr[44], 255);
        ctx->gpr[43] = spu_selb(ctx->gpr[42], ctx->gpr[41], ctx->gpr[39]);
        ctx->gpr[40] = spu_selb(ctx->gpr[38], ctx->gpr[39], ctx->gpr[37]);
        spu_ls_write128(ctx, 0xAD0, ctx->gpr[37]);
        /* sync */;
        { ctx->pc = 0x1120; spu_func_00001120(ctx); return; }
}

void spu_func_00001120(spu_context* ctx) {
        ctx->gpr[5] = spu_ori(ctx->gpr[11], 0);
        ctx->gpr[50] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[3] = spu_ila(0x100);
        ctx->gpr[11] = spu_il(2560);
        ctx->gpr[4] = spu_rotqbyi(ctx->gpr[50], 8);
        ctx->gpr[0] = spu_splat_u32(0x1138); ctx->pc = ctx->gpr[11]._u32[0]; spu_indirect_branch(ctx);
        ctx->gpr[1] = spu_ila(0x3FFD0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[0] = spu_splat_u32(0x1144); spu_func_00000B90(ctx);
        ctx->gpr[0] = spu_splat_u32(0x1148); spu_func_00000FE8(ctx);
        { ctx->pc = 0x1148; spu_func_00001148(ctx); return; }
}

void spu_func_00001148(spu_context* ctx) {
        ctx->gpr[1] = spu_ila(0x3FFD0);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_ls_read128(ctx, 0xAC0);
        ctx->gpr[5] = spu_cdd(ctx->gpr[1], 0);
        ctx->gpr[6] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[5] = spu_selb(ctx->gpr[4], ctx->gpr[8], ctx->gpr[7]);
        ctx->gpr[6] = spu_selb(ctx->gpr[3], ctx->gpr[7], ctx->gpr[2]);
        ctx->gpr[3] = spu_fsmbi(0x1000);
        spu_ls_write128(ctx, 0xAC0, ctx->gpr[2]);
        ctx->gpr[3] = spu_andbi(ctx->gpr[3], 32);
        ctx->gpr[0] = spu_splat_u32(0x1174); spu_func_00000FE8(ctx);
        /* nop */;
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000B90u, spu_func_00000B90, "spu_func_00000B90" },
    { 0x00000BF8u, spu_func_00000BF8, "spu_func_00000BF8" },
    { 0x00000EACu, spu_func_00000EAC, "spu_func_00000EAC" },
    { 0x00000EC8u, spu_func_00000EC8, "spu_func_00000EC8" },
    { 0x00000F04u, spu_func_00000F04, "spu_func_00000F04" },
    { 0x00000FB8u, spu_func_00000FB8, "spu_func_00000FB8" },
    { 0x00000FCCu, spu_func_00000FCC, "spu_func_00000FCC" },
    { 0x00000FE8u, spu_func_00000FE8, "spu_func_00000FE8" },
    { 0x00001120u, spu_func_00001120, "spu_func_00001120" },
    { 0x00001148u, spu_func_00001148, "spu_func_00001148" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
