/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_func_00003010(spu_context* ctx);
void spu_func_00003040(spu_context* ctx);
void spu_func_00003050(spu_context* ctx);
void spu_func_000030D8(spu_context* ctx);
void spu_func_000030E4(spu_context* ctx);
void spu_func_00003120(spu_context* ctx);
void spu_func_00003160(spu_context* ctx);
void spu_func_000031A0(spu_context* ctx);
void spu_func_0000322C(spu_context* ctx);
void spu_func_00003238(spu_context* ctx);
void spu_func_000032A8(spu_context* ctx);
void spu_func_00003348(spu_context* ctx);
void spu_func_000033D8(spu_context* ctx);
void spu_func_000033EC(spu_context* ctx);
void spu_func_000033F0(spu_context* ctx);
void spu_func_00003408(spu_context* ctx);
void spu_func_00003410(spu_context* ctx);
void spu_func_00003418(spu_context* ctx);
void spu_func_00003428(spu_context* ctx);
void spu_func_0000342C(spu_context* ctx);
void spu_func_00003458(spu_context* ctx);
void spu_func_0000349C(spu_context* ctx);
void spu_func_000034B0(spu_context* ctx);
void spu_func_0000353C(spu_context* ctx);
void spu_func_00003544(spu_context* ctx);
void spu_func_00003558(spu_context* ctx);
void spu_func_00003580(spu_context* ctx);
void spu_func_00003598(spu_context* ctx);
void spu_func_000035F0(spu_context* ctx);
void spu_func_00003690(spu_context* ctx);
void spu_func_000036B8(spu_context* ctx);
void spu_func_000036F0(spu_context* ctx);
void spu_func_00003700(spu_context* ctx);
void spu_func_00003730(spu_context* ctx);
void spu_func_00003798(spu_context* ctx);
void spu_func_00003818(spu_context* ctx);
void spu_func_00003878(spu_context* ctx);
void spu_func_00003950(spu_context* ctx);
void spu_func_000039DC(spu_context* ctx);
void spu_func_000039EC(spu_context* ctx);
void spu_func_00003A38(spu_context* ctx);
void spu_func_00003A64(spu_context* ctx);
void spu_func_00003A80(spu_context* ctx);
void spu_func_00003D38(spu_context* ctx);
void spu_func_00003E20(spu_context* ctx);
void spu_func_00003E60(spu_context* ctx);
void spu_func_00003EA8(spu_context* ctx);
void spu_func_00003EF0(spu_context* ctx);
void spu_func_00003F28(spu_context* ctx);
void spu_func_00003F48(spu_context* ctx);
void spu_func_00003F78(spu_context* ctx);
void spu_func_00003FF4(spu_context* ctx);
void spu_func_00004028(spu_context* ctx);
void spu_func_00004048(spu_context* ctx);
void spu_func_00004058(spu_context* ctx);
void spu_func_000040AC(spu_context* ctx);
void spu_func_000040C0(spu_context* ctx);
void spu_func_000041A8(spu_context* ctx);
void spu_func_000042C8(spu_context* ctx);
void spu_func_000043A8(spu_context* ctx);
void spu_func_000043D8(spu_context* ctx);
void spu_func_000043F4(spu_context* ctx);
void spu_func_00004410(spu_context* ctx);
void spu_func_0000448C(spu_context* ctx);
void spu_func_000044E0(spu_context* ctx);
void spu_func_000044F0(spu_context* ctx);
void spu_func_00004540(spu_context* ctx);
void spu_func_0000458C(spu_context* ctx);
void spu_func_000045B4(spu_context* ctx);
void spu_func_00004608(spu_context* ctx);
void spu_func_000046AC(spu_context* ctx);
void spu_func_00004720(spu_context* ctx);
void spu_func_00004750(spu_context* ctx);
void spu_func_000047E8(spu_context* ctx);
void spu_func_00004810(spu_context* ctx);
void spu_func_0000483C(spu_context* ctx);
void spu_func_00004858(spu_context* ctx);
void spu_func_00004890(spu_context* ctx);
void spu_func_000048C0(spu_context* ctx);
void spu_func_00004950(spu_context* ctx);
void spu_func_000049C8(spu_context* ctx);
void spu_func_000049D0(spu_context* ctx);
void spu_func_00004A08(spu_context* ctx);
void spu_func_00004A6C(spu_context* ctx);
void spu_func_00004A98(spu_context* ctx);
void spu_func_00004AE8(spu_context* ctx);
void spu_func_00004B30(spu_context* ctx);
void spu_func_00004B80(spu_context* ctx);
void spu_func_00004B98(spu_context* ctx);
void spu_func_00004BE4(spu_context* ctx);
void spu_func_00004C10(spu_context* ctx);
void spu_func_00004C28(spu_context* ctx);
void spu_func_00004D00(spu_context* ctx);
void spu_func_00004DC8(spu_context* ctx);
void spu_func_00004E10(spu_context* ctx);
void spu_func_00004E20(spu_context* ctx);
void spu_func_00004EF8(spu_context* ctx);
void spu_func_00005008(spu_context* ctx);
void spu_func_00005060(spu_context* ctx);
void spu_func_00005110(spu_context* ctx);
void spu_func_0000533C(spu_context* ctx);
void spu_func_00005398(spu_context* ctx);
void spu_func_000053B4(spu_context* ctx);
void spu_func_000053C8(spu_context* ctx);
void spu_func_000053E8(spu_context* ctx);
void spu_func_00005424(spu_context* ctx);
void spu_func_00005490(spu_context* ctx);
void spu_func_000054B8(spu_context* ctx);
void spu_func_000054E0(spu_context* ctx);
void spu_func_00005588(spu_context* ctx);
void spu_func_00005590(spu_context* ctx);
void spu_func_00005618(spu_context* ctx);
void spu_func_00005628(spu_context* ctx);
void spu_func_00005798(spu_context* ctx);
void spu_func_000057B8(spu_context* ctx);
void spu_func_00005800(spu_context* ctx);
void spu_func_00005810(spu_context* ctx);
void spu_func_00005850(spu_context* ctx);
void spu_func_0000586C(spu_context* ctx);
void spu_func_00005880(spu_context* ctx);
void spu_func_00005890(spu_context* ctx);
void spu_func_000058B0(spu_context* ctx);
void spu_func_000058C4(spu_context* ctx);
void spu_func_000058E0(spu_context* ctx);
void spu_func_00005988(spu_context* ctx);
void spu_func_000059B0(spu_context* ctx);
void spu_func_000059F0(spu_context* ctx);
void spu_func_00005A98(spu_context* ctx);
void spu_func_00005AC0(spu_context* ctx);
void spu_func_00005AF4(spu_context* ctx);
void spu_func_00005B28(spu_context* ctx);
void spu_func_00005B58(spu_context* ctx);
void spu_func_00005B78(spu_context* ctx);
void spu_func_00005C08(spu_context* ctx);
void spu_func_00005C18(spu_context* ctx);
void spu_func_00005C50(spu_context* ctx);
void spu_func_00005C90(spu_context* ctx);
void spu_func_00005D14(spu_context* ctx);
void spu_func_00005D1C(spu_context* ctx);
void spu_func_00005D34(spu_context* ctx);
void spu_func_00005D4C(spu_context* ctx);
void spu_func_00005D74(spu_context* ctx);
void spu_func_00005D7C(spu_context* ctx);
void spu_func_00005D98(spu_context* ctx);
void spu_func_00005DE8(spu_context* ctx);
void spu_func_00005DF0(spu_context* ctx);
void spu_func_00005E30(spu_context* ctx);
void spu_func_00005E40(spu_context* ctx);
void spu_func_00005E48(spu_context* ctx);
void spu_func_00005ED8(spu_context* ctx);
void spu_func_00005F08(spu_context* ctx);
void spu_func_00005F40(spu_context* ctx);
void spu_func_00005FC8(spu_context* ctx);
void spu_func_00006004(spu_context* ctx);
void spu_func_00006030(spu_context* ctx);
void spu_func_00006050(spu_context* ctx);
void spu_func_00006064(spu_context* ctx);
void spu_func_00006098(spu_context* ctx);
void spu_func_000060A0(spu_context* ctx);
void spu_func_000060C8(spu_context* ctx);
void spu_func_00006194(spu_context* ctx);
void spu_func_000061B4(spu_context* ctx);
void spu_func_000061B8(spu_context* ctx);
void spu_func_00006344(spu_context* ctx);
void spu_func_0000639C(spu_context* ctx);
void spu_func_000063A0(spu_context* ctx);
void spu_func_00006484(spu_context* ctx);
void spu_func_0000648C(spu_context* ctx);
void spu_func_000064FC(spu_context* ctx);
void spu_func_00006508(spu_context* ctx);
void spu_func_00006514(spu_context* ctx);
void spu_func_0000651C(spu_context* ctx);
void spu_func_00006558(spu_context* ctx);
void spu_func_000065FC(spu_context* ctx);
void spu_func_00006798(spu_context* ctx);
void spu_func_000067CC(spu_context* ctx);
void spu_func_00006814(spu_context* ctx);
void spu_func_0000684C(spu_context* ctx);
void spu_func_0000689C(spu_context* ctx);
void spu_func_000068B0(spu_context* ctx);
void spu_func_000068E0(spu_context* ctx);
void spu_func_000069AC(spu_context* ctx);
void spu_func_000069CC(spu_context* ctx);
void spu_func_000069D0(spu_context* ctx);
void spu_func_00006B5C(spu_context* ctx);
void spu_func_00006BB4(spu_context* ctx);
void spu_func_00006BB8(spu_context* ctx);
void spu_func_00006C9C(spu_context* ctx);
void spu_func_00006CA4(spu_context* ctx);
void spu_func_00006D14(spu_context* ctx);
void spu_func_00006D20(spu_context* ctx);
void spu_func_00006D2C(spu_context* ctx);
void spu_func_00006D34(spu_context* ctx);
void spu_func_00006D70(spu_context* ctx);
void spu_func_00006E20(spu_context* ctx);
void spu_func_00007004(spu_context* ctx);
void spu_func_00007038(spu_context* ctx);
void spu_func_0000707C(spu_context* ctx);
void spu_func_000070B4(spu_context* ctx);
void spu_func_00007104(spu_context* ctx);
void spu_func_00007118(spu_context* ctx);
void spu_func_00007148(spu_context* ctx);
void spu_func_00007188(spu_context* ctx);
void spu_func_000071D0(spu_context* ctx);
void spu_func_00007228(spu_context* ctx);
void spu_func_00007230(spu_context* ctx);
void spu_func_000072C4(spu_context* ctx);
void spu_func_0000739C(spu_context* ctx);
void spu_func_000073C0(spu_context* ctx);
void spu_func_000073CC(spu_context* ctx);
void spu_func_000073E8(spu_context* ctx);
void spu_func_000073EC(spu_context* ctx);
void spu_func_00007400(spu_context* ctx);
void spu_func_00007498(spu_context* ctx);
void spu_func_000074D0(spu_context* ctx);
void spu_func_00007540(spu_context* ctx);
void spu_func_00007568(spu_context* ctx);
void spu_func_00007598(spu_context* ctx);
void spu_func_000075A8(spu_context* ctx);
void spu_func_000075C8(spu_context* ctx);
void spu_func_000075D0(spu_context* ctx);
void spu_func_00007610(spu_context* ctx);
void spu_func_00007628(spu_context* ctx);
void spu_func_00007658(spu_context* ctx);
void spu_func_00007680(spu_context* ctx);
void spu_func_00007720(spu_context* ctx);
void spu_func_00007728(spu_context* ctx);
void spu_func_00007730(spu_context* ctx);
void spu_func_00007770(spu_context* ctx);
void spu_func_000077B4(spu_context* ctx);
void spu_func_000077C0(spu_context* ctx);
void spu_func_00008F10(spu_context* ctx); /* external */
void spu_func_00008F20(spu_context* ctx); /* external */
void spu_func_00008F30(spu_context* ctx); /* external */
void spu_func_00008F40(spu_context* ctx); /* external */
void spu_func_00008F50(spu_context* ctx); /* external */
void spu_func_00008F60(spu_context* ctx); /* external */
void spu_func_00008F70(spu_context* ctx); /* external */
void spu_func_0000AA00(spu_context* ctx); /* external */
void spu_func_0000DE80(spu_context* ctx); /* external */
void spu_func_0000DFE0(spu_context* ctx); /* external */
void spu_func_0003FFF0(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_recomp_register(void);
