/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_func_00000000(spu_context* ctx);
void spu_func_00000110(spu_context* ctx); /* external */
void spu_func_00000140(spu_context* ctx); /* external */
void spu_func_00000220(spu_context* ctx); /* external */
void spu_func_00000260(spu_context* ctx); /* external */
void spu_func_000002A0(spu_context* ctx); /* external */
void spu_func_00000830(spu_context* ctx); /* external */
void spu_func_00000898(spu_context* ctx); /* external */
void spu_func_00000918(spu_context* ctx); /* external */
void spu_func_00000978(spu_context* ctx); /* external */
void spu_func_00000E38(spu_context* ctx); /* external */
void spu_func_00002E98(spu_context* ctx); /* external */
void spu_func_00003198(spu_context* ctx); /* external */
void spu_func_000031A0(spu_context* ctx); /* external */
void spu_func_000031C8(spu_context* ctx); /* external */
void spu_func_00003658(spu_context* ctx); /* external */
void spu_func_000039E0(spu_context* ctx); /* external */
void spu_func_00003E70(spu_context* ctx); /* external */
void spu_func_00004248(spu_context* ctx); /* external */
void spu_func_00004330(spu_context* ctx); /* external */
void spu_func_00004500(spu_context* ctx); /* external */
void spu_func_00004598(spu_context* ctx); /* external */
void spu_func_00004640(spu_context* ctx); /* external */
void spu_func_00004668(spu_context* ctx); /* external */
void spu_func_00004758(spu_context* ctx); /* external */
void spu_func_00004870(spu_context* ctx); /* external */
void spu_func_000048C0(spu_context* ctx); /* external */
void spu_func_00007B00(spu_context* ctx); /* external */
void spu_func_0000AF80(spu_context* ctx); /* external */
void spu_func_0000B0E0(spu_context* ctx); /* external */
void spu_func_00015BB0(spu_context* ctx); /* external */
void spu_func_00015BB4(spu_context* ctx); /* external */
void spu_func_00015BB8(spu_context* ctx); /* external */
void spu_func_00015BBC(spu_context* ctx); /* external */
void spu_func_00017D7C(spu_context* ctx); /* external */
void spu_func_0001ECDC(spu_context* ctx); /* external */
void spu_func_0001F4DC(spu_context* ctx); /* external */
void spu_func_0001FE0C(spu_context* ctx); /* external */
void spu_func_0003D0F0(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_recomp_register(void);
