/*
 * ps3recomp - PPU runtime loader
 *
 * The runtime half of the static recompiler's PPU side. It provides everything
 * the lifted code (ppu_recomp.c, generated by ppu_lifter.py) expects from "the
 * game project":
 *
 *   - big-endian guest memory accessors (vm_read / vm_write),
 *   - the address -> function registry + ps3_indirect_call dispatch,
 *   - the cross-fragment trampoline TLS pointer,
 *   - an lv2_syscall stub,
 *   - an ELF image loader (PT_LOAD -> vm_base, BSS zeroed),
 *   - OPD resolution ({u32 func, u32 toc}) and a run entry point.
 *
 * Game-agnostic: works on any decrypted PS3 PPU ELF. `vm_base` is owned by the
 * host (allocated large enough to cover the highest segment vaddr+memsz).
 *
 * Compiled as C++ to match the lifted output's `extern "C"` / __declspec(thread).
 */

#include "ppu_recomp.h"     /* ppu_context, func decls, ppu_recomp_register */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern "C" uint8_t* vm_base;   /* defined by the host */

/* Guest address-space size (host sets this); 0 = unchecked. Bounds-checking
 * turns a stray pointer in lifted code into a logged bad-access returning 0
 * instead of a host segfault -- so a first-boot run reveals the next wall
 * rather than dying. */
extern "C" uint32_t ppu_vm_size = 0;

/* PT_TLS template (captured by ppu_load_elf) + the main thread's TLS image.
 * PPC64 ELF TLS: r13 (thread pointer) = image_base + 0x7000. The image sits in
 * the free window just below the mmapper region (0x11000000) and above any
 * game's high data segments, so it doesn't collide with the static image. */
static uint32_t g_tls_vaddr = 0, g_tls_filesz = 0, g_tls_memsz = 0;
#define PPU_TLS_IMG   0x10F00000u
#define PPU_TLS_TP    (PPU_TLS_IMG + 0x7000u)

#ifdef _WIN32
#include <windows.h>
#endif
static int vm_oob(uint32_t a, uint32_t n)
{
    if (ppu_vm_size && (uint64_t)a + n > ppu_vm_size) {
        static int logged = 0;
        if (logged < 40) {
            fprintf(stderr, "[vm] OOB access 0x%08X (+%u)\n", a, n);
#ifdef _WIN32
            /* one-shot backtrace on the first OOB so the lifted caller is known */
            static int bt = 0;
            if (bt++ < 3) {
                void* fr[20]; USHORT m = RtlCaptureStackBackTrace(0, 20, fr, NULL);
                HMODULE self = NULL;
                GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                   GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                   (LPCSTR)&vm_oob, &self);
                for (USHORT i = 0; i < m; i++) {
                    HMODULE mm = NULL;
                    GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)fr[i], &mm);
                    if (mm == self)
                        fprintf(stderr, "[vm-oob]   #%-2u rva=0x%llX\n", i,
                                (unsigned long long)((char*)fr[i] - (char*)self));
                }
            }
#endif
            logged++;
        }
        return 1;
    }
    return 0;
}

/* ---------------------------------------------------------------------------
 * Big-endian guest memory accessors (PPU is big-endian; vm_base holds the
 * guest image in its native byte order).
 * -----------------------------------------------------------------------*/
/* Shared read-frequency histogram (YDKJ_HOTMAP): finds busy-loop polled
 * addresses across all read widths even when the loop touches several addresses
 * per iteration (so the consecutive HOTREAD detectors reset). */
static void vm_hotmap(uint32_t ea, int width)
{
    static int en = -1; if (en < 0) en = getenv("YDKJ_HOTMAP") ? 1 : 0;
    if (!en) return;
    enum { NB = 4096 };
    static uint32_t addr[NB]; static uint32_t cnt[NB]; static unsigned long long tot = 0;
    uint32_t h = (ea >> 2) & (NB - 1);
    if (addr[h] != ea) { addr[h] = ea; cnt[h] = 0; }
    cnt[h]++;
    if ((++tot % 8000000ull) == 0) {
        uint32_t b1 = 0, b2 = 0;
        for (uint32_t i = 0; i < NB; i++) if (cnt[i] > cnt[b1]) b1 = i;
        for (uint32_t i = 0; i < NB; i++) if (i != b1 && cnt[i] > cnt[b2]) b2 = i;
        fprintf(stderr, "[HOTMAP] hottest read: 0x%08X (%ux) | 2nd 0x%08X (%ux) [w=%d]\n",
                addr[b1], cnt[b1], addr[b2], cnt[b2], width);
        for (uint32_t i = 0; i < NB; i++) cnt[i] = 0;
    }
}
extern "C" {
uint8_t  vm_read8 (uint64_t a) { if (vm_oob((uint32_t)a,1)) return 0; vm_hotmap((uint32_t)a,1);
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 2000000ull)==0) fprintf(stderr, "[sample] read8  0x%08X ra0=%p ra1=%p\n", (uint32_t)a, __builtin_return_address(0), __builtin_return_address(1)); }
#endif
    { static __declspec(thread) uint32_t last=0xFFFFFFFFu; static __declspec(thread) uint32_t n=0;
      if ((uint32_t)a==last) { if (++n==200000) { fprintf(stderr, "[HOTREAD8] spinning on 0x%08X\n", (uint32_t)a); n=0; } }
      else { last=(uint32_t)a; n=0; } }
    return vm_base[(uint32_t)a]; }
uint16_t vm_read16(uint64_t a) { if (vm_oob((uint32_t)a,2)) return 0; vm_hotmap((uint32_t)a,2); uint16_t v; memcpy(&v, vm_base + (uint32_t)a, 2);
    { static __declspec(thread) uint32_t last=0xFFFFFFFFu; static __declspec(thread) uint32_t n=0;
      if ((uint32_t)a==last) { if (++n==200000) { fprintf(stderr, "[HOTREAD16] spinning on 0x%08X\n", (uint32_t)a); n=0; } } else { last=(uint32_t)a; n=0; } }
    return __builtin_bswap16(v); }
uint32_t vm_read32(uint64_t a) { if (vm_oob((uint32_t)a,4)) return 0; uint32_t v; memcpy(&v, vm_base + (uint32_t)a, 4);
    { static int64_t rw=-2; if (rw==-2) { const char* e=getenv("YDKJ_RWATCH"); rw=e?(int64_t)strtoul(e,0,0):-1; }
      if (rw>=0) { uint32_t ea=(uint32_t)a; if (ea>=(uint32_t)rw && ea<(uint32_t)rw+0x80) {
        static int _n=0; if (_n++<40) fprintf(stderr,"[RWATCH] read32 0x%08X = 0x%08X  ra=%p\n", ea, __builtin_bswap32(v), __builtin_return_address(0)); } } }
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 4000000ull)==0) fprintf(stderr, "[sample] read32 0x%08X = 0x%08X\n", (uint32_t)a, __builtin_bswap32(v)); }
#endif
    /* Frequency histogram (YDKJ_HOTMAP): find busy-loop polled addresses even
     * when the loop reads several addresses per iteration (so the consecutive
     * HOTREAD detector resets). Dumps the hottest addresses periodically. */
    { static int en=-1; if (en<0) en = getenv("YDKJ_HOTMAP") ? 1 : 0;
      if (en) { enum { NB=2048 }; static uint32_t addr[NB]; static uint32_t cnt[NB];
        static uint64_t tot=0; uint32_t ea=(uint32_t)a; uint32_t h=(ea>>2)&(NB-1);
        if (addr[h]!=ea){addr[h]=ea;cnt[h]=0;} cnt[h]++;
        if ((++tot % 20000000ull)==0) {
          uint32_t bi=0; for(uint32_t i=0;i<NB;i++) if(cnt[i]>cnt[bi]) bi=i;
          uint32_t b2=(bi+1)&(NB-1); for(uint32_t i=0;i<NB;i++) if(i!=bi && cnt[i]>cnt[b2]) b2=i;
          fprintf(stderr,"[HOTMAP] hottest read32: 0x%08X (%ux)  2nd: 0x%08X (%ux)\n",
                  addr[bi],cnt[bi],addr[b2],cnt[b2]);
          for(uint32_t i=0;i<NB;i++) cnt[i]=0; } } }
    /* Hot-poll detector: a thread spinning on the same address (e.g. a GCM FIFO
     * get-pointer / label waiting on RSX) reads it thousands of times in a row. */
    { static __declspec(thread) uint32_t last=0xFFFFFFFFu; static __declspec(thread) uint32_t n=0;
      if ((uint32_t)a==last) { if (++n==200000) { fprintf(stderr, "[HOTREAD] spinning on 0x%08X (=0x%08X)\n", (uint32_t)a, __builtin_bswap32(v)); n=0; } }
      else { last=(uint32_t)a; n=0; } }
    return __builtin_bswap32(v); }
uint64_t vm_read64(uint64_t a) { if (vm_oob((uint32_t)a,8)) return 0; vm_hotmap((uint32_t)a,8); uint64_t v; memcpy(&v, vm_base + (uint32_t)a, 8);
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 2000000ull)==0) fprintf(stderr, "[sample] read64 0x%08X\n", (uint32_t)a); }
#endif
    { static __declspec(thread) uint32_t last=0xFFFFFFFFu; static __declspec(thread) uint32_t n=0;
      if ((uint32_t)a==last) { if (++n==200000) { fprintf(stderr, "[HOTREAD64] spinning on 0x%08X\n", (uint32_t)a); n=0; } } else { last=(uint32_t)a; n=0; } }
    return __builtin_bswap64(v); }
void vm_write8 (uint64_t a, uint8_t  v) { if (vm_oob((uint32_t)a,1)) return; vm_base[(uint32_t)a] = v; }
void vm_write16(uint64_t a, uint16_t v) { if (vm_oob((uint32_t)a,2)) return; v = __builtin_bswap16(v); memcpy(vm_base + (uint32_t)a, &v, 2); }
void vm_write32(uint64_t a, uint32_t v) { if (vm_oob((uint32_t)a,4)) return;
    { static int64_t w=-2; if (w==-2) { const char* e=getenv("YDKJ_WWATCH"); w = e?(int64_t)strtoul(e,0,0):-1; }
      if (w>=0) { uint32_t ea=(uint32_t)a; if (ea>=(uint32_t)w && ea<(uint32_t)w+0x40)
        fprintf(stderr,"[WWATCH] write32 0x%08X = 0x%08X  ra=%p\n", ea, v, __builtin_return_address(0)); } }
    v = __builtin_bswap32(v); memcpy(vm_base + (uint32_t)a, &v, 4); }
void vm_write64(uint64_t a, uint64_t v) { if (vm_oob((uint32_t)a,8)) return; v = __builtin_bswap64(v); memcpy(vm_base + (uint32_t)a, &v, 8); }
}

/* Cross-fragment trampoline pointer (matches the lifted header's TLS decl). */
extern "C" __declspec(thread) void (*g_trampoline_fn)(void*) = nullptr;

/* Per-thread active guest context, for the crash handler to report the guest PC
 * (ctx->pc, updated by lifted code at block boundaries) of a host AV. */
extern "C" __declspec(thread) ppu_context* g_active_ctx = nullptr;

/* ---------------------------------------------------------------------------
 * Function registry: guest code address -> lifted host function.
 * Open-addressing hash (load factor kept low). Large retail titles exceed 64k
 * lifted functions (Minecraft 37k, LittleBigPlanet 68k), so the table MUST be
 * larger than any title's function count or the insert probe below never finds
 * a free slot and spins forever at startup. 2^18 = 262144 slots keeps a 68k
 * image at ~26% load with headroom to ~190k functions at 75%.
 * -----------------------------------------------------------------------*/
typedef void (*ppu_fn)(ppu_context*);

#define PPU_HASH_BITS 18
#define PPU_HASH_SIZE (1u << PPU_HASH_BITS)
#define PPU_HASH_MASK (PPU_HASH_SIZE - 1)

static uint32_t g_addr[PPU_HASH_SIZE];
static ppu_fn   g_fn[PPU_HASH_SIZE];
static uint32_t g_fn_count = 0;

extern "C" void ppu_register_function(uint64_t addr, ppu_fn fn)
{
    uint32_t a = (uint32_t)addr;
    uint32_t i = (a * 2654435761u) & PPU_HASH_MASK;
    /* Bounded probe: never loop past the whole table. A full table (function
     * count >= PPU_HASH_SIZE) would otherwise spin forever here at startup. */
    for (uint32_t probes = 0; probes < PPU_HASH_SIZE; probes++) {
        if (g_fn[i] == nullptr) { g_addr[i] = a; g_fn[i] = fn; g_fn_count++; return; }
        if (g_addr[i] == a) { g_fn[i] = fn; return; }   /* overwrite */
        i = (i + 1) & PPU_HASH_MASK;
    }
    static int warned = 0;
    if (warned++ < 4)
        fprintf(stderr, "[ppu] function table full (%u/%u) -- raise PPU_HASH_BITS; "
                "0x%08X dropped\n", g_fn_count, (unsigned)PPU_HASH_SIZE, a);
}

static ppu_fn ppu_lookup(uint32_t a)
{
    uint32_t i = (a * 2654435761u) & PPU_HASH_MASK;
    for (uint32_t probes = 0; probes < PPU_HASH_SIZE; probes++) {
        if (g_fn[i] == nullptr) return nullptr;
        if (g_addr[i] == a) return g_fn[i];
        i = (i + 1) & PPU_HASH_MASK;
    }
    return nullptr;
}

extern "C" uint32_t ppu_function_count(void) { return g_fn_count; }

/* Bridge the lifter-emitted function_table[] (declared in ppu_recomp.h) into the
 * address->function hash map. The host boot harness calls this once at startup. */
extern "C" void ppu_recomp_register(void)
{
    for (uint64_t i = 0; i < function_table_count; i++)
        ppu_register_function(function_table[i].addr, function_table[i].func);
}

/* Indirect call (bctrl/bctr): CTR holds the already-OPD-resolved code address. */
extern "C" void ps3_indirect_call(ppu_context* ctx)
{
    g_active_ctx = ctx;
    uint32_t addr = (uint32_t)ctx->ctr;
    /* Null / return-to-OS sentinel: a bctr to address 0 means the guest
     * unwound to the initial frame (or a not-yet-populated function pointer).
     * Don't treat it as an unresolved call -- just return to the caller. */
    if (addr == 0)
        return;

    ppu_fn fn = ppu_lookup(addr);
    if (fn) {
        /* Recursion-depth guard: a malformed/cyclic jump table (or a tail-call
         * chain that never converges) can dispatch recursively without bound
         * and blow the host stack. Cap the depth, log once, then unwind. */
        static thread_local int s_depth = 0;
        if (s_depth > 4000) {
            static int warned = 0;
            if (warned++ < 8)
                fprintf(stderr, "[ppu] recursion cap @0x%08X depth=%d -- skipping\n", addr, s_depth);
            return;
        }
        s_depth++;
        fn(ctx);
        /* Drain the tail-call trampoline chain. Lifted functions model a tail
         * call (`b target`) by setting g_trampoline_fn and returning, expecting
         * the *caller's* DRAIN_TRAMPOLINE to continue. An indirect call IS such
         * a caller: if the dispatched function ends in a tail call, the
         * continuation is lost unless we drain it here too -- ppu_run only
         * drains the top frame, so without this the CRT's init tail-calls (and
         * the function-pointer tables they populate) silently never run. */
        while (g_trampoline_fn) {
            void (*tf)(void*) = g_trampoline_fn;
            g_trampoline_fn = 0;
            tf(ctx);
        }
        s_depth--;
        return;
    }
    /* Stuck-loop guard: a divergence (e.g. an object with a null function
     * pointer) can make the game spin on the same unresolved target forever.
     * Detect a long run of identical unresolved targets and bail so the run
     * stays fast and the log readable. */
    static uint32_t last = 0xFFFFFFFFu; static uint32_t streak = 0;
    uint32_t cur = (uint32_t)ctx->ctr;
    if (cur == last) {
        if (++streak == 2000) { fprintf(stderr, "[ppu] FATAL: stuck calling 0x%08X (%u times) -- aborting run\n", cur, streak); fflush(stderr); exit(3); }
        return;   /* don't spam the log on a tight retry loop */
    }
    last = cur; streak = 0;
    fprintf(stderr, "[ppu] unresolved indirect call -> 0x%08X\n", (uint32_t)ctx->ctr);
    static int dumped = 0;
    if (dumped < 3) {
        dumped++;
        { void* ra = __builtin_return_address(0); HMODULE m=NULL;
          GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS|GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,(LPCSTR)ra,&m);
          fprintf(stderr, "      host_ra=%p rva=0x%llX (llvm-symbolizer --obj=ydkj_boot.exe)\n",
                ra, (unsigned long long)((uintptr_t)ra-(uintptr_t)m)); }
        fprintf(stderr, "      lr=0x%08X r2=0x%08X r3=0x%08X r11=0x%08X r12=0x%08X\n",
                (uint32_t)ctx->lr, (uint32_t)ctx->gpr[2], (uint32_t)ctx->gpr[3],
                (uint32_t)ctx->gpr[11], (uint32_t)ctx->gpr[12]);
        for (int r = 0; r < 32; r += 8)
            fprintf(stderr, "      r%-2d: %08X %08X %08X %08X %08X %08X %08X %08X\n", r,
                (uint32_t)ctx->gpr[r+0],(uint32_t)ctx->gpr[r+1],(uint32_t)ctx->gpr[r+2],(uint32_t)ctx->gpr[r+3],
                (uint32_t)ctx->gpr[r+4],(uint32_t)ctx->gpr[r+5],(uint32_t)ctx->gpr[r+6],(uint32_t)ctx->gpr[r+7]);
    }
}

/* Called when lifted code branches to a function that wasn't in this lift
 * (subset/incremental builds). Logs the first few; returns so execution can
 * continue (the result is undefined, but it won't crash the link). */
extern "C" void ppu_unlifted_stub(uint64_t addr, ppu_context* ctx)
{
    (void)ctx;
    static int logged = 0;
    if (logged < 20) {
        fprintf(stderr, "[ppu] call to unlifted function 0x%08X\n", (uint32_t)addr);
        logged++;
    }
}

/* The real lv2 syscall table (runtime/syscalls/lv2_register.c). */
extern "C" int lv2_try_syscall(ppu_context* ctx);

/* lv2 syscall dispatch: r11 = syscall number, args in r3.. (PPC ABI).
 * A few syscalls the CRT needs at boot are handled inline (boot-tuned); the
 * rest are dispatched to the real lv2 table, and only genuinely-unregistered
 * numbers fall through to the return-CELL_OK stub. */
extern "C" void lv2_syscall(ppu_context* ctx)
{
    uint64_t num = ctx->gpr[11];
    if (getenv("YDKJ_SCTRACE"))
        fprintf(stderr, "[sc] %llu r3=%08X r4=%08X r5=%08X r6=%08X\n",
                (unsigned long long)num, (uint32_t)ctx->gpr[3], (uint32_t)ctx->gpr[4],
                (uint32_t)ctx->gpr[5], (uint32_t)ctx->gpr[6]);
    switch (num) {
    case 352: {   /* sys_memory_get_user_memory_size(sys_memory_info_t* info)
                   * info = { u32 total_user_memory; u32 available_user_memory } */
        uint32_t info = (uint32_t)ctx->gpr[3];
        if (info) { vm_write32(info + 0, 0x10000000u);   /* 256 MB total */
                    vm_write32(info + 4, 0x0C000000u); } /* 192 MB available */
        ctx->gpr[3] = 0;
        return;
    }
    case 330: {   /* sys_mmapper_allocate_address(u64 size, u64 flags,
                   * u64 alignment, u32* alloc_addr) -> reserve guest VA range */
        static uint32_t s_next_va = 0x11000000u;   /* just past the loaded image */
        uint32_t size  = (uint32_t)ctx->gpr[3];
        uint32_t align = (uint32_t)ctx->gpr[5];
        uint32_t out   = (uint32_t)ctx->gpr[6];
        if (align < 0x100000u) align = 0x100000u;   /* 1 MB min */
        s_next_va = (s_next_va + align - 1) & ~(align - 1);
        uint32_t va = s_next_va;
        s_next_va += (size + 0xFFFFFu) & ~0xFFFFFu;
        if (out) vm_write32(out, va);
        ctx->gpr[3] = 0;
        return;
    }
    case 988:     /* sys_tty_write — canonical LV2 number (psdevwiki); some CRTs
                   * use this instead of 403. Same ABI. */
    case 403: {   /* sys_tty_write(s32 ch, cptr buf, u32 len, ptr pwritelen) */
        uint32_t ch   = (uint32_t)ctx->gpr[3];
        uint32_t buf  = (uint32_t)ctx->gpr[4];
        uint32_t len  = (uint32_t)ctx->gpr[5];
        uint32_t pwl  = (uint32_t)ctx->gpr[6];
        uint32_t wlen = len;
        if (wlen > 0x4000u) {   /* guard against garbage len (divergence dumps memory) */
            static int n = 0;
            if (n < 20) { fprintf(stderr, "[tty] suspicious len=%u (buf=0x%08X) clamped\n", len, buf); n++; }
            wlen = 0x4000u;
        }
        FILE* out = stdout;   /* keep all TTY on stdout, clean of [ppu] logs */
        for (uint32_t i = 0; i < wlen; i++) {
            if (ppu_vm_size && buf + i >= ppu_vm_size) break;
            fputc(vm_read8(buf + i), out);
        }
        fflush(out);
        if (pwl) vm_write32(pwl, len);
        ctx->gpr[3] = 0;
        return;
    }
    default: {
        /* Consult the real lv2 syscall table (semaphore / mutex / cond /
         * rwlock / event / timer / memory / vm / fs / spu). Initialised by
         * lv2_init_syscalls() at boot. Unregistered numbers fall through to the
         * return-0 stub below (which is what got the CRT this far). */
        if (lv2_try_syscall(ctx))
            return;
        static int logged = 0;
        if (logged < 30) {
            fprintf(stderr, "[ppu] lv2_syscall %llu (stub)\n", (unsigned long long)num);
            logged++;
        }
        ctx->gpr[3] = 0;   /* CELL_OK */
        return;
    }
    }
}

/* ---------------------------------------------------------------------------
 * Minimal big-endian ELF64 loader: copies PT_LOAD segments into vm_base at
 * their vaddrs and zero-fills BSS (memsz > filesz). Returns e_entry (an OPD
 * address) or 0 on error. Assumes vm_base is allocated large enough.
 * -----------------------------------------------------------------------*/
static uint16_t be16(const uint8_t* p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint32_t be32(const uint8_t* p) { return ((uint32_t)p[0] << 24) | (p[1] << 16) | (p[2] << 8) | p[3]; }
static uint64_t be64(const uint8_t* p) { return ((uint64_t)be32(p) << 32) | be32(p + 4); }

extern "C" uint32_t ppu_load_elf(const char* path)
{
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "[ppu] cannot open %s\n", path); return 0; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* file = (uint8_t*)malloc(sz);
    if (!file || fread(file, 1, sz, f) != (size_t)sz) { fclose(f); free(file); return 0; }
    fclose(f);

    if (sz < 64 || memcmp(file, "\x7F""ELF", 4) != 0 || file[4] != 2 /*ELFCLASS64*/ || file[5] != 2 /*MSB*/) {
        fprintf(stderr, "[ppu] not a 64-bit big-endian ELF\n"); free(file); return 0;
    }
    uint64_t fsz = (uint64_t)sz;
    uint32_t entry = (uint32_t)be64(file + 24);
    uint64_t phoff = be64(file + 32);
    uint16_t phentsize = be16(file + 54);
    uint16_t phnum = be16(file + 56);

    int loaded = 0;
    for (uint16_t i = 0; i < phnum; i++) {
        uint64_t ph_off = phoff + (uint64_t)i * phentsize;
        if (ph_off + 56 > fsz) break;   /* program header itself out of the file */
        const uint8_t* ph = file + ph_off;
        uint32_t p_type = be32(ph + 0);
        if (p_type == 7 /*PT_TLS*/) {
            /* The thread-local template: its initialised bytes live in vm_base
             * at p_vaddr (covered by a PT_LOAD too). ppu_run copies it into the
             * main thread's TLS image and points r13 at it. */
            g_tls_vaddr  = (uint32_t)be64(ph + 16);
            g_tls_filesz = (uint32_t)be64(ph + 32);
            g_tls_memsz  = (uint32_t)be64(ph + 40);
            fprintf(stderr, "[ppu] PT_TLS template vaddr=0x%08X filesz=0x%X memsz=0x%X\n",
                    g_tls_vaddr, g_tls_filesz, g_tls_memsz);
            continue;
        }
        if (p_type != 1 /*PT_LOAD*/) continue;
        uint64_t p_offset = be64(ph + 8);
        uint64_t p_vaddr  = be64(ph + 16);
        uint64_t p_filesz = be64(ph + 32);
        uint64_t p_memsz  = be64(ph + 40);
        if (p_memsz == 0) continue;
        /* Bounds-check both ends before touching host memory: the source range
         * must lie inside the ELF file, and the destination range inside the
         * guest VM (ppu_vm_size==0 = unchecked, matching the vm accessors).
         * Skip malformed/oversized segments rather than overflowing the host. */
        if (p_offset > fsz || p_filesz > fsz || p_offset + p_filesz > fsz) {
            fprintf(stderr, "[ppu] segment %u file range 0x%llX+0x%llX exceeds ELF (0x%llX), skipped\n",
                    i, (unsigned long long)p_offset, (unsigned long long)p_filesz, (unsigned long long)fsz);
            continue;
        }
        if (ppu_vm_size && (p_vaddr > ppu_vm_size || p_memsz > ppu_vm_size ||
                            p_vaddr + p_memsz > ppu_vm_size)) {
            fprintf(stderr, "[ppu] segment %u vaddr 0x%llX+0x%llX exceeds VM (0x%X), skipped\n",
                    i, (unsigned long long)p_vaddr, (unsigned long long)p_memsz, ppu_vm_size);
            continue;
        }
        memcpy(vm_base + (uint32_t)p_vaddr, file + p_offset, (size_t)p_filesz);
        if (p_memsz > p_filesz)
            memset(vm_base + (uint32_t)p_vaddr + (uint32_t)p_filesz, 0, (size_t)(p_memsz - p_filesz));
        loaded++;
    }
    free(file);
    fprintf(stderr, "[ppu] loaded %d PT_LOAD segments, entry OPD 0x%08X\n", loaded, entry);
    return entry;
}

/* Resolve an OPD descriptor {u32 func, u32 toc}. */
extern "C" int ppu_opd_resolve(uint32_t opd, uint32_t* code, uint32_t* toc)
{
    uint32_t c = vm_read32(opd);
    uint32_t t = vm_read32(opd + 4);
    if (code) *code = c;
    if (toc)  *toc  = t;
    return c != 0;
}

/* Run from an entry OPD: set up r1 (stack) + r2 (TOC) and dispatch the entry
 * code address. Returns 0 if it ran, -1 if the entry function isn't registered. */
/* Entry trampoline for sys_ppu_thread_create'd threads. The lv2 thread layer
 * (syscalls/sys_ppu_thread.c) spawns a host thread, fills ctx (cia = entry OPD,
 * r3 = arg, stack), and calls this. We resolve the OPD -> {code,toc} the same
 * way the main entry does and dispatch into the recompiled function, draining
 * the tail-call trampoline chain so the thread body fully runs. */
extern "C" void (*g_ppu_thread_entry_trampoline)(ppu_context*);
static void ppu_thread_entry_trampoline(ppu_context* ctx)
{
    uint32_t code = 0, toc = 0;
    ppu_opd_resolve((uint32_t)ctx->cia, &code, &toc);
    if (toc) ctx->gpr[2] = toc;
    if (!ctx->gpr[13]) ctx->gpr[13] = PPU_TLS_TP;   /* share main TLS for now */
    ppu_fn fn = ppu_lookup(code);
    if (!fn) {
        fprintf(stderr, "[ppu] thread entry 0x%08X (cia=0x%08X) not registered\n",
                code, (uint32_t)ctx->cia);
        return;
    }
    g_active_ctx = ctx;
    fn(ctx);
    while (g_trampoline_fn) { void (*tf)(void*) = g_trampoline_fn; g_trampoline_fn = 0; tf(ctx); }
}

/* Call a guest function by OPD with up to 4 integer args, on a private scratch
 * stack, and return r3. Used by the HLE runtime to deliver callbacks into
 * recompiled code (cellSysutil events, GCM vblank/flip handlers, ...) -- the
 * mechanism behind g_ps3_guest_caller (ps3emu/guest_call.h). */
extern "C" uint64_t ppu_guest_call(uint32_t opd_addr,
                                   uint64_t a0, uint64_t a1, uint64_t a2, uint64_t a3)
{
    if (!opd_addr) return 0;
    uint32_t code = 0, toc = 0;
    ppu_opd_resolve(opd_addr, &code, &toc);
    ppu_fn fn = ppu_lookup(code);
    if (!fn) { fprintf(stderr, "[ppu] guest_call: OPD 0x%08X -> code 0x%08X not registered\n",
                       opd_addr, code); return 0; }

    /* Private scratch stack high in the guest stack region, distinct from the
     * main + ppu_thread stacks. One callback at a time per caller thread. */
    static __declspec(thread) uint32_t s_cb_sp = 0;
    if (!s_cb_sp) s_cb_sp = 0xCFFE0000u;

    ppu_context ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.gpr[1]  = s_cb_sp;
    ctx.gpr[2]  = toc;
    ctx.gpr[3]  = a0; ctx.gpr[4] = a1; ctx.gpr[5] = a2; ctx.gpr[6] = a3;
    ctx.gpr[13] = PPU_TLS_TP;
    ctx.cia     = code;
    g_active_ctx = &ctx;
    g_active_ctx = &ctx;
    fn(&ctx);
    while (g_trampoline_fn) { void (*tf)(void*) = g_trampoline_fn; g_trampoline_fn = 0; tf(&ctx); }
    return ctx.gpr[3];
}

extern "C" int ppu_run(uint32_t entry_opd, uint32_t stack_top)
{
    g_ppu_thread_entry_trampoline = ppu_thread_entry_trampoline;
    uint32_t code = 0, toc = 0;
    ppu_opd_resolve(entry_opd, &code, &toc);
    ppu_fn fn = ppu_lookup(code);
    if (!fn) { fprintf(stderr, "[ppu] entry code 0x%08X not registered\n", code); return -1; }

    ppu_context ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.gpr[1] = stack_top;   /* stack pointer */
    ctx.gpr[2] = toc;         /* TOC base (r2) */

    /* PS3 process-entry ABI: the loader hands _start register state the CRT
     * (_initialize) consumes directly:
     *   r7..r10 = TLS descriptor (thread_id, seg vaddr, seg filesz, memsz),
     *             forwarded to sys_initialize_tls;
     *   r12     = the lv2 page size (1 MB), stored to the global lv2_page_size
     *             and used as the malloc granularity. Without it the SDK heap
     *             (dinkum malloc) has granularity 0 and every allocation fails
     *             (observed: cellmark's memalign returns NULL, no sys_memory
     *             call is ever made). Values come from the ELF PT_TLS captured
     *             by ppu_load_elf. */
    ctx.gpr[7]  = 1;               /* main thread id */
    ctx.gpr[8]  = g_tls_vaddr;     /* TLS segment vaddr  */
    ctx.gpr[9]  = g_tls_filesz;    /* TLS segment filesz */
    ctx.gpr[10] = g_tls_memsz;     /* TLS segment memsz  */
    ctx.gpr[12] = 0x100000;        /* lv2 page size (1 MB) -> malloc granularity */

    /* Main-thread TLS: copy the PT_TLS template into the TLS image (zeroing the
     * BSS tail) and point r13 at TP. The CRT accesses thread-locals relative to
     * r13; without this they hit address ~0 and corrupt the boot. */
    if (g_tls_memsz && (PPU_TLS_IMG + g_tls_memsz < (ppu_vm_size ? ppu_vm_size : 0x11000000u))) {
        memcpy(vm_base + PPU_TLS_IMG, vm_base + g_tls_vaddr, g_tls_filesz);
        if (g_tls_memsz > g_tls_filesz)
            memset(vm_base + PPU_TLS_IMG + g_tls_filesz, 0, g_tls_memsz - g_tls_filesz);
        ctx.gpr[13] = PPU_TLS_TP;
        fprintf(stderr, "[ppu] TLS image 0x%08X (r13/TP=0x%08X)\n", PPU_TLS_IMG, PPU_TLS_TP);
    }
    fprintf(stderr, "[ppu] run: code 0x%08X, toc 0x%08X, sp 0x%08X\n", code, toc, stack_top);
    g_active_ctx = &ctx;
    fn(&ctx);
    while (g_trampoline_fn) { void (*tf)(void*) = g_trampoline_fn; g_trampoline_fn = 0; tf(&ctx); }
    return 0;
}
