/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000000(spu_context* ctx) {
        ctx->gpr[10] = spu_ai(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_il(512);
        ctx->gpr[4] = spu_il(0);
        ctx->gpr[5] = spu_ai(ctx->gpr[10], 0);
        ctx->gpr[6] = spu_il(16);
        ctx->gpr[7] = spu_il(0);
        ctx->gpr[8] = spu_il(64);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[3]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[4]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[5]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[6]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[7]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[8]);
        ctx->gpr[5] = spu_ai(ctx->gpr[10], 64);
        ctx->gpr[8] = spu_il(32);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[3]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[4]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[5]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[6]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[7]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[8]);
        ctx->gpr[11] = spu_il(2778);
        spu_wrch(ctx, SPU_WrOutIntrMbox, ctx->gpr[11]);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000000u, spu_func_00000000, "spu_func_00000000" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
