/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_func_00000000(spu_context* ctx);
void spu_func_00000018(spu_context* ctx);
void spu_func_00000030(spu_context* ctx);
void spu_func_00000080(spu_context* ctx);
void spu_func_00000088(spu_context* ctx);
void spu_func_000000D0(spu_context* ctx);
void spu_func_00000150(spu_context* ctx);
void spu_func_00000158(spu_context* ctx);
void spu_func_000001B8(spu_context* ctx);
void spu_func_00000268(spu_context* ctx);
void spu_func_00000270(spu_context* ctx);
void spu_func_000002D8(spu_context* ctx);
void spu_func_000003E8(spu_context* ctx);
void spu_func_000003F8(spu_context* ctx);
void spu_func_00000500(spu_context* ctx);
void spu_func_00000540(spu_context* ctx);
void spu_func_00000558(spu_context* ctx);
void spu_func_00000608(spu_context* ctx);
void spu_func_000006E8(spu_context* ctx);
void spu_func_00000838(spu_context* ctx);
void spu_func_000008A0(spu_context* ctx);
void spu_func_00000AC0(spu_context* ctx);
void spu_func_00000B58(spu_context* ctx);
void spu_func_00000E28(spu_context* ctx);
void spu_func_00000F40(spu_context* ctx);
void spu_func_00000F58(spu_context* ctx);
void spu_func_00001230(spu_context* ctx);
void spu_func_000012BC(spu_context* ctx);
void spu_func_000012D4(spu_context* ctx);
void spu_func_000012E8(spu_context* ctx);
void spu_func_000012F0(spu_context* ctx);
void spu_func_000013A8(spu_context* ctx);
void spu_func_000013C0(spu_context* ctx);
void spu_func_000015EC(spu_context* ctx);
void spu_func_000015F0(spu_context* ctx);
void spu_func_000015F8(spu_context* ctx);
void spu_func_00001600(spu_context* ctx);
void spu_func_000016F8(spu_context* ctx);
void spu_func_000017D0(spu_context* ctx);
void spu_func_00001A28(spu_context* ctx);
void spu_func_00001F48(spu_context* ctx);
void spu_func_00002570(spu_context* ctx);
void spu_func_00002640(spu_context* ctx);
void spu_func_00002700(spu_context* ctx);
void spu_func_000027C0(spu_context* ctx);
void spu_func_00002848(spu_context* ctx);
void spu_func_000028B8(spu_context* ctx);
void spu_func_00002998(spu_context* ctx);
void spu_func_000029A0(spu_context* ctx);
void spu_func_00002D00(spu_context* ctx);
void spu_func_00002D90(spu_context* ctx);
void spu_func_00002DA0(spu_context* ctx);
void spu_func_00002DB8(spu_context* ctx);
void spu_func_00002DC8(spu_context* ctx);
void spu_func_00002EC8(spu_context* ctx);
void spu_func_00002F14(spu_context* ctx);
void spu_func_000030E8(spu_context* ctx);
void spu_func_00003288(spu_context* ctx);
void spu_func_00003410(spu_context* ctx);
void spu_func_00003640(spu_context* ctx);
void spu_func_00003748(spu_context* ctx);
void spu_func_0000375C(spu_context* ctx);
void spu_func_00003918(spu_context* ctx);
void spu_func_00003C38(spu_context* ctx);
void spu_func_00003F48(spu_context* ctx);
void spu_func_000042D8(spu_context* ctx);
void spu_func_000044B8(spu_context* ctx);
void spu_func_00004730(spu_context* ctx);
void spu_func_00004B78(spu_context* ctx);
void spu_func_00004FA8(spu_context* ctx);
void spu_func_00005180(spu_context* ctx);
void spu_func_000051E0(spu_context* ctx);
void spu_func_000052E4(spu_context* ctx);
void spu_func_000052F8(spu_context* ctx);
void spu_func_00005348(spu_context* ctx);
void spu_func_00005370(spu_context* ctx);
void spu_func_000054A0(spu_context* ctx);
void spu_func_000055B0(spu_context* ctx);
void spu_func_000055D8(spu_context* ctx);
void spu_func_000056A0(spu_context* ctx);
void spu_func_00005748(spu_context* ctx);
void spu_func_00005770(spu_context* ctx);
void spu_func_000057A0(spu_context* ctx);
void spu_func_000057D0(spu_context* ctx);
void spu_func_00005890(spu_context* ctx);
void spu_func_000058C8(spu_context* ctx);
void spu_func_000058DC(spu_context* ctx);
void spu_func_00005910(spu_context* ctx);
void spu_func_000059B8(spu_context* ctx);
void spu_func_000059E0(spu_context* ctx);
void spu_func_00005A14(spu_context* ctx);
void spu_func_00005B10(spu_context* ctx);
void spu_func_00005C98(spu_context* ctx);
void spu_func_00005DC8(spu_context* ctx);
void spu_func_00005F30(spu_context* ctx);
void spu_func_00005F40(spu_context* ctx);
void spu_func_00006040(spu_context* ctx);
void spu_func_00006050(spu_context* ctx);
void spu_func_00006278(spu_context* ctx);
void spu_func_00006518(spu_context* ctx);
void spu_func_000067F8(spu_context* ctx);
void spu_func_00006A60(spu_context* ctx);
void spu_func_00006CA0(spu_context* ctx);
void spu_func_00006EC0(spu_context* ctx);
void spu_func_00007110(spu_context* ctx);
void spu_func_00007120(spu_context* ctx);
void spu_func_000071D0(spu_context* ctx);
void spu_func_000071E0(spu_context* ctx);
void spu_func_00007288(spu_context* ctx);
void spu_func_000072C0(spu_context* ctx);
void spu_func_00007388(spu_context* ctx);
void spu_func_000073F8(spu_context* ctx);
void spu_func_00007420(spu_context* ctx);
void spu_func_00007428(spu_context* ctx);
void spu_func_00007518(spu_context* ctx);
void spu_func_000076E8(spu_context* ctx);
void spu_func_00007910(spu_context* ctx);
void spu_func_000079C8(spu_context* ctx);
void spu_func_000079D8(spu_context* ctx);
void spu_func_00007A48(spu_context* ctx);
void spu_func_00007CB4(spu_context* ctx);
void spu_func_00007E08(spu_context* ctx);
void spu_func_00007E18(spu_context* ctx);
void spu_func_00007E70(spu_context* ctx);
void spu_func_00008020(spu_context* ctx);
void spu_func_00008090(spu_context* ctx);
void spu_func_00008160(spu_context* ctx);
void spu_func_000081B0(spu_context* ctx);
void spu_func_000081C0(spu_context* ctx);
void spu_func_000083CC(spu_context* ctx);
void spu_func_00008438(spu_context* ctx);
void spu_func_00008470(spu_context* ctx);
void spu_func_000084F0(spu_context* ctx);
void spu_func_0000855C(spu_context* ctx);
void spu_func_00008648(spu_context* ctx);
void spu_func_000086F0(spu_context* ctx);
void spu_func_00008710(spu_context* ctx);
void spu_func_00008734(spu_context* ctx);
void spu_func_00008760(spu_context* ctx);
void spu_func_00008780(spu_context* ctx);
void spu_func_000087A4(spu_context* ctx);
void spu_func_000087D0(spu_context* ctx);
void spu_func_000087F8(spu_context* ctx);
void spu_func_0000881C(spu_context* ctx);
void spu_func_00008890(spu_context* ctx);
void spu_func_000088A0(spu_context* ctx);
void spu_func_00008AF0(spu_context* ctx);
void spu_func_00008B60(spu_context* ctx);
void spu_func_00008B80(spu_context* ctx);
void spu_func_00008B90(spu_context* ctx);
void spu_func_00008BC0(spu_context* ctx);
void spu_func_00008BE0(spu_context* ctx);
void spu_func_00008C48(spu_context* ctx);
void spu_func_00008CF0(spu_context* ctx);
void spu_func_00008D18(spu_context* ctx);
void spu_func_00008D50(spu_context* ctx);
void spu_func_00008D90(spu_context* ctx);
void spu_func_00008DA8(spu_context* ctx);
void spu_func_00008E50(spu_context* ctx);
void spu_func_00008E78(spu_context* ctx);
void spu_func_00008EB0(spu_context* ctx);
void spu_func_00008F58(spu_context* ctx);
void spu_func_00008F80(spu_context* ctx);
void spu_func_00008FB8(spu_context* ctx);
void spu_func_00008FD8(spu_context* ctx);
void spu_func_00008FF8(spu_context* ctx);
void spu_func_00009014(spu_context* ctx);
void spu_func_00009040(spu_context* ctx);
void spu_func_000090A0(spu_context* ctx);
void spu_func_00009110(spu_context* ctx);
void spu_func_0000912C(spu_context* ctx);
void spu_func_000091B0(spu_context* ctx);
void spu_func_0000A3C0(spu_context* ctx);
void spu_func_0000A3D0(spu_context* ctx);
void spu_func_0000A3E0(spu_context* ctx);
void spu_func_0000A3F0(spu_context* ctx);

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_recomp_register(void);
