#!/usr/bin/env python3
"""
Generate the HLE NID -> handler registration unit from the /* NID: 0x.. */
annotations in the HLE library sources.

For each annotated function it emits a `ps3_hle_register(nid, "name", name)`
call inside `ppu_hle_register_all()` (the strong override of the weak default
in ppu_hle.cpp). The matching library headers are #included so the symbols are
declared.

Usage:
    python gen_hle_nids.py --out gen/ppu_hle_nids.cpp cellGcmSys [cellSysutil ...]
    (lib names resolve to libs/**/<name>.c and the sibling <name>.h)
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nid_database import compute_nid

# Non-static, top-level definitions of exported-looking functions. The NID is
# COMPUTED from the name (the firmware-correct algorithm in nid_database.py),
# not read from a /* NID */ comment -- computation matches the real imports far
# better and needs no manual annotation.
DEF_RE = re.compile(
    r"^(?!static)[A-Za-z_][\w \t\*]*?\b(_?(?:cell|sys|sce|_sys)\w+)\s*\([^;]*?\)\s*\{",
    re.M)


def scan(c_path):
    txt = open(c_path, encoding="latin1").read()
    out = []
    for m in DEF_RE.finditer(txt):
        name = m.group(1)
        out.append((compute_nid(name), name))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("libs", nargs="+")
    ap.add_argument("--out", default="ppu_hle_nids.cpp")
    args = ap.parse_args()

    headers, regs, seen = [], [], set()
    for lib in args.libs:
        cs = glob.glob(os.path.join(ROOT, "libs", "**", lib + ".c"), recursive=True)
        if not cs:
            print(f"warning: {lib}.c not found"); continue
        c = cs[0]
        h = os.path.splitext(c)[0] + ".h"
        if os.path.exists(h):
            headers.append(os.path.relpath(h, ROOT).replace("\\", "/"))
        for nid, name in scan(c):
            if nid in seen:
                continue
            seen.add(nid)
            regs.append((nid, name))

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("/* Auto-generated by gen_hle_nids.py -- do not edit. */\n")
        f.write('extern "C" void ps3_hle_register(unsigned int nid, const char* name, void* handler);\n')
        for h in headers:
            f.write(f'#include "{os.path.basename(h)}"\n')
        f.write('extern "C" void ppu_hle_register_all(void) {\n')
        for nid, name in regs:
            f.write(f'    ps3_hle_register(0x{nid:08X}u, "{name}", (void*){name});\n')
        f.write("}\n")
    print(f"wrote {args.out}: {len(regs)} NID handlers from {len(headers)} header(s)")


if __name__ == "__main__":
    main()
