#!/usr/bin/env python3
"""prx_exports.py — emit a PRX's export table as a C array for the PRX loader.

Reads a PRX's SCE module-info export tables (via elf_parser) and writes a
`prx_export` array of {nid, base-0 vaddr} pairs plus a count. The runtime
loader registers these as NID -> (load_base + vaddr), so a title's NID-import
resolver can dispatch into the loaded module (see runtime/prx/prx_loader.h).

Function exports point at an OPD; var exports at data. The loader treats both
uniformly (the indirect dispatcher walks an OPD; data vars are read directly).

Usage:
    prx_exports.py <prx> --symbol libsre --out libsre_exports.c [--json out.json]
"""
import argparse, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import elf_parser


def collect_exports(prx_path):
    f = elf_parser.ELFFile(prx_path)
    f.load()
    out = []  # (nid, vaddr, lib, kind)
    for e in f.exports:
        lib = e.name_str or "(module)"
        nfun = e.num_funcs
        for idx, (nid, addr) in enumerate(zip(e.nids, e.addrs)):
            kind = "func" if idx < nfun else "var"
            out.append((nid, addr, lib, kind))
    return f.module_info.name if f.module_info else "?", out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("prx")
    ap.add_argument("--symbol", required=True,
                    help="C identifier prefix, e.g. 'libsre' -> libsre_exports[]")
    ap.add_argument("--out", required=True, help="output C file")
    ap.add_argument("--json", help="also write a JSON dump")
    args = ap.parse_args()

    modname, exports = collect_exports(args.prx)

    lines = [
        "/* Auto-generated by tools/prx_exports.py from %s (module '%s')."
        % (os.path.basename(args.prx), modname),
        " * NID -> base-0 vaddr export table for the runtime PRX loader. */",
        '#include "prx_loader.h"',
        "",
        "/* C linkage + explicit `extern` so the table matches an extern \"C\"",
        " * declaration and keeps EXTERNAL linkage whether built as C or C++",
        " * (a bare file-scope `const` has internal linkage in C++). */",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "extern const prx_export %s_exports[];" % args.symbol,
        "extern const uint32_t %s_export_count;" % args.symbol,
        "",
        "const prx_export %s_exports[] = {" % args.symbol,
    ]
    for nid, addr, lib, kind in exports:
        lines.append("    { 0x%08X, 0x%06X },  /* %-10s %s */" % (nid, addr, lib, kind))
    lines.append("};")
    lines.append("const uint32_t %s_export_count = %d;" % (args.symbol, len(exports)))
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))

    if args.json:
        with open(args.json, "w") as fh:
            json.dump([{"nid": "0x%08X" % n, "vaddr": "0x%X" % a,
                        "lib": l, "kind": k} for n, a, l, k in exports],
                      fh, indent=2)

    libs = {}
    for _, _, l, _ in exports:
        libs[l] = libs.get(l, 0) + 1
    print("module '%s': %d exports across %d libraries" %
          (modname, len(exports), len(libs)))
    for l, c in sorted(libs.items(), key=lambda x: -x[1]):
        print("  %-20s %d" % (l, c))
    print("-> %s" % args.out)


if __name__ == "__main__":
    main()
