#!/usr/bin/env python3
"""
SPU instruction lifter -- translates SPU disassembly into C code for the
ps3recomp static-recompilation runtime.

Mirrors the design of ppu_lifter.py:
  * Each original SPU function is emitted as a C function taking a
    ``spu_context*`` parameter (see runtime/spu/spu_context.h).
  * Instruction semantics live in small ``static inline u128 spu_*`` helper
    functions emitted into the source preamble; the per-instruction
    translator just wires guest registers to those helpers.  This keeps the
    generated function bodies readable and the semantics unit-testable.
  * Control flow uses the same trampoline pattern as the PPU lifter to avoid
    unbounded host-stack growth on backward branches.

SPU register model
------------------
  * 128 registers, each a 128-bit ``u128`` union (lanes: _u32[4], _u16[8],
    _u8[16], _s32[4], _f32[4], ...).
  * Most arithmetic is SIMD across the natural lane width (word = 4x32,
    halfword = 8x16, byte = 16x8).
  * Scalar / addressing instructions use the *preferred slot* = word lane 0
    (``reg._u32[0]``), matching spu_preferred_u32() in spu_context.h.

Scope (Phase 1)
---------------
Implemented faithfully: immediates, integer add/sub (word+half, +imm),
bitwise logic (+imm), compares (eq/gt/lgt for byte/half/word, +imm), select
(selb), byte shuffle (shufb), count-leading-zeros / popcount, the common
shift/rotate-immediate forms, single-precision float add/sub/mul and the
fused multiply forms, quadword load/store (d-form, absolute, indexed),
branches (relative/absolute/conditional/indirect, with link), stop/nop/sync.

Emitted as runtime calls (declared extern, implemented by the runtime):
channel ops (rdch/wrch/rchcnt -> MFC DMA, mailboxes, signals) and indirect
branch dispatch.

Anything not yet handled is emitted as a ``/* TODO spu: ... */`` comment so
the gap is visible in the generated source and counted in the CLI summary.

Usage:
    python spu_lifter.py <input_bin> [--base ADDR] [--output dir]
                         [--functions FILE]
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from spu_disasm import SPUInstruction, disassemble_spu, spu_decode, CHANNEL_NAMES
except ImportError:
    print("Error: spu_disasm.py must be in the same directory.", file=sys.stderr)
    sys.exit(1)

# Channel macro names defined in runtime/spu/spu_context.h. When the
# disassembler hands us one of these, we can emit it verbatim as a macro.
_CHANNEL_MACROS = set(CHANNEL_NAMES.values())

# ---------------------------------------------------------------------------
# C preambles
# ---------------------------------------------------------------------------

HEADER_PREAMBLE = """\
/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif
"""

# NOTE on endianness: spu_context.h treats word lane 0 as the preferred slot
# and its local-store helpers copy raw bytes (big-endian in the guest image).
# The helpers below operate lane-wise, which is internally consistent as long
# as loads/stores use the same lane convention. A host that is not big-endian
# will need byte-swapping in the LS helpers -- that is a runtime concern, out
# of scope for the lifter.
SOURCE_PREAMBLE = """/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"
"""

# ---------------------------------------------------------------------------
# Operand helpers
# ---------------------------------------------------------------------------

def _ops(operands: str) -> list[str]:
    return [o.strip() for o in operands.split(",") if o.strip()]


def _reg(token: str) -> str:
    """'$r12' -> '12'."""
    m = re.match(r"\$r(\d+)", token.strip())
    return m.group(1) if m else token.strip()


def _disp_base(token: str):
    """'0x10($r4)' or '-0x10($r4)' -> ('0x10', '4')."""
    m = re.match(r"(-?0x[0-9A-Fa-f]+|-?\d+)\(\$r(\d+)\)", token.strip())
    if m:
        return m.group(1), m.group(2)
    return None, None


def _imm(token: str) -> str:
    token = token.strip()
    if token.startswith("0x") or token.startswith("-0x"):
        return token
    try:
        return str(int(token))
    except ValueError:
        return token


def _chan(token: str) -> str:
    """Channel operand -> a C expression (macro name or numeric id)."""
    token = token.strip()
    if token in _CHANNEL_MACROS:
        return token
    m = re.match(r"ch(\d+)", token)
    if m:
        return m.group(1)
    return token

# ---------------------------------------------------------------------------
# Lifter
# ---------------------------------------------------------------------------

@dataclass
class LiftedFunction:
    name: str = ""
    start_addr: int = 0
    end_addr: int = 0
    body_lines: list[str] = field(default_factory=list)
    calls: list[int] = field(default_factory=list)


# Mnemonics whose last operand is a branch target address (0x...).
_COND_BR = {"brz", "brnz", "brhz", "brhnz"}


# Mnemonics that do NOT write the rt register (so we skip the post-trace).
# Everything else writes rt = ops[0] (= insn.raw & 0x7F).
_NO_RT_WRITE = {
    "stop", "stopd", "lnop", "nop", "sync", "dsync",
    "bi", "iret", "biz", "binz", "bihz", "bihnz",
    "br", "bra", "brz", "brnz", "brhz", "brhnz",
    "hbr", "hbra", "hbrr",
    "stqd", "stqa", "stqr", "stqx",
    "wrch",
    "hgt", "hlgt", "heq", "hgti", "hlgti", "heqi",
}


def _bi_target_reg(insn):
    """Return the branch-target register of a bi/biz/binz/... insn, or None."""
    ops = _ops(insn.operands)
    if insn.mnemonic == "bi" and ops:
        return _reg(ops[0])
    if insn.mnemonic in ("biz", "binz", "bihz", "bihnz") and len(ops) >= 2:
        return _reg(ops[1])
    return None


# RRR (4-operand) SPU ops write their destination in bits 21-27; the low 7 bits
# (raw & 0x7F) are the RC *source* for these. Every other format writes bits 0-6.
_RRR_DEST_OPS = {"selb", "shufb", "mpya", "fnms", "fma", "fms"}

def _dest_reg(insn) -> int:
    """The register an instruction writes (rt), accounting for RRR-format ops
    whose destination is bits 21-27 rather than the low 7 bits."""
    if insn.mnemonic in _RRR_DEST_OPS:
        return (insn.raw >> 21) & 0x7F
    return insn.raw & 0x7F


def compute_bi_r0_jumps(insns, bounds) -> set:
    """`bi $r0` (and conditional `biz/binz $r0`) is normally a function RETURN
    (r0 = link register). But Sony's SPU code also uses it as a COMPUTED TAIL
    JUMP after reloading r0 from memory -- e.g. the SPURS taskset launch
    `lqa $r0, savedContextLr(0x2C80) ... bi $r0` jumps to the task entry
    (0x3050), NOT back to the caller. Mistranslating that as `return;` makes
    the launch fall through and the taskset dispatcher loop forever (same bug
    class as the brsl mislifts). Detect it: within each function, a `bi $r0`
    is a computed jump iff the NEAREST preceding write to r0 is an ABSOLUTE
    load (lqa/lqr). A genuine return restores the link via a register/stack
    load (lqd/lqx) or never rewrites r0 -- those stay returns. Returns the
    set of such bi addrs."""
    jumps = set()
    for (s, e) in bounds:
        fn = sorted((i for i in insns if s <= i.addr < e), key=lambda x: x.addr)
        for idx, insn in enumerate(fn):
            if _bi_target_reg(insn) != "0":
                continue
            # backward scan for the nearest instruction that writes r0
            for j in range(idx - 1, -1, -1):
                w = fn[j]
                if w.mnemonic not in _NO_RT_WRITE and _dest_reg(w) == 0:
                    if w.mnemonic in ("lqa", "lqr"):
                        jumps.add(insn.addr)
                    break  # nearest r0 writer found; classification decided
    return jumps


class SPULifter:
    def __init__(self, trace: bool = False, prefix: str = ""):
        self.functions: list[LiftedFunction] = []
        self.call_targets: set[int] = set()
        self.branch_targets: set[int] = set()
        self.unsupported: dict[str, int] = {}
        self.trace = trace
        # Symbol prefix for all emitted spu_func_* / spu_recomp_register symbols.
        # Lets multiple lifted SPU images link into one binary without collisions
        # (every image otherwise exports spu_func_00000090 etc.). Empty = legacy.
        self.prefix = prefix
        # Addresses of `bi/biz/... $r0` that are COMPUTED TAIL JUMPS (r0 reloaded
        # via lqa/lqr), not function returns -- see compute_bi_r0_jumps(). Empty
        # set => every `bi $r0` is a return (the prior behaviour).
        self.bi_r0_jump: set = set()

    # ------------------------------------------------------------------ #
    def lift_function(self, insns: list[SPUInstruction],
                      start: int, end: int) -> LiftedFunction:
        func = LiftedFunction(name=f"{self.prefix}spu_func_{start:08X}",
                              start_addr=start, end_addr=end)

        internal: set[int] = set()
        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            tgt = self._branch_target(insn)
            if tgt is not None and start <= tgt < end:
                internal.add(tgt)

        last_insn = None
        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            if insn.addr in internal:
                func.body_lines.append(f"loc_{insn.addr:08X}:")
            c = self._translate(insn, func)
            if c:
                if self.trace:
                    func.body_lines.append(f"    spu_trace_pc(ctx, 0x{insn.addr:X});")
                func.body_lines.append(f"    {c}")
                if self.trace and insn.mnemonic not in _NO_RT_WRITE:
                    rt_idx = insn.raw & 0x7F
                    func.body_lines.append(f"    spu_trace_rt(ctx, {rt_idx});")
            last_insn = insn

        # Fall-through chaining: if the final instruction does NOT unconditionally
        # end the basic block (i.e. it's a normal op, a call brsl/bisl, or a
        # conditional branch whose not-taken path continues), execution proceeds
        # into the next sequential function. Emit a tail-call so the chain isn't
        # truncated (this was silently dropping execution mid-job).
        _TERMINATORS = {"br", "bra", "bi", "iret", "stop", "stopd"}
        if (last_insn is not None and last_insn.mnemonic not in _TERMINATORS
                and end in getattr(self, "func_starts", set())):
            func.body_lines.append(
                f"    {{ ctx->pc = 0x{end:X}; {self.prefix}spu_func_{end:08X}(ctx); return; }}")

        # Infinite no-op self-loop (the SPU `br .` halt idiom): a function whose
        # whole body is nops + an unconditional branch back into itself does
        # nothing but spin. The default lifting renders it as `goto loc_<x>` --
        # an infinite C loop that hangs the SPU host thread forever (e.g. the
        # SPURS task runtime's terminal/idle state). Render it as a clean abort
        # (spu_halt longjmps back to the dispatcher) so the host thread returns.
        body_insns = [i for i in insns if start <= i.addr < end]
        if body_insns and all(i.mnemonic in ("nop", "lnop", "br", "bra")
                              for i in body_insns):
            last = body_insns[-1]
            ltgt = self._branch_target(last)
            if (last.mnemonic in ("br", "bra") and ltgt is not None
                    and start <= ltgt < end):
                func.body_lines = [
                    "    /* infinite no-op self-loop (SPU halt idiom) -> abort */",
                    "    spu_halt(ctx); return;",
                ]

        self.functions.append(func)
        return func

    @staticmethod
    def _branch_target(insn: SPUInstruction):
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        tok = None
        if mn in ("br", "brsl", "bra", "brasl") and ops:
            tok = ops[0]
        elif mn in _COND_BR and ops:
            tok = ops[-1]
        if tok and tok.startswith("0x"):
            try:
                return int(tok, 16)
            except ValueError:
                return None
        return None

    # ------------------------------------------------------------------ #
    def _translate(self, insn: SPUInstruction, func: LiftedFunction) -> str:
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        addr = insn.addr

        def rt(): return _reg(ops[0])
        def ra(): return _reg(ops[1])
        def rb(): return _reg(ops[2])
        def g(i): return f"ctx->gpr[{i}]"

        # ---- nop / sync / stop ----
        if mn in ("nop", "lnop"):
            return "/* nop */;"
        if mn in ("sync", "dsync"):
            return "/* sync */;"
        if mn == "fscrwr":
            return "/* fscrwr: FP status/control write (no-op in recomp) */;"
        if mn == "stop":
            return "ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;"

        # ---- immediate loaders ----
        if mn == "il":
            return f"{g(rt())} = spu_il({_imm(ops[1])});"
        if mn == "ila":
            return f"{g(rt())} = spu_ila({_imm(ops[1])});"
        if mn == "ilh":
            return f"{g(rt())} = spu_ilh({_imm(ops[1])});"
        if mn == "ilhu":
            return f"{g(rt())} = spu_ilhu({_imm(ops[1])});"
        if mn == "iohl":
            return f"{g(rt())} = spu_iohl({g(rt())}, {_imm(ops[1])});"
        if mn == "fsmbi":
            return f"{g(rt())} = spu_fsmbi({_imm(ops[1])});"

        # addx / bgx: read rt as carry-in (and write rt)
        if mn == "addx":
            return f"{g(rt())} = spu_addx({g(ra())}, {g(rb())}, {g(rt())});"
        if mn == "bgx":
            return f"{g(rt())} = spu_bgx({g(ra())}, {g(rb())}, {g(rt())});"

        # Halt-on-condition + stopd: pure stop semantics in recompiled code;
        # we just continue execution (no host halt path for these yet).
        if mn in ("hgti", "hlgti", "heqi", "hgt", "hlgt", "heq"):
            return f"/* {mn}: halt-on-condition (no-op in recomp) */;"
        if mn == "stopd":
            return "ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;"

        # ---- integer arithmetic (register) ----
        rr_bin = {
            "a": "spu_a", "sf": "spu_sf", "ah": "spu_ah", "sfh": "spu_sfh",
            "and": "spu_and", "or": "spu_or", "xor": "spu_xor",
            "nand": "spu_nand", "nor": "spu_nor", "andc": "spu_andc", "orc": "spu_orc",
            "ceq": "spu_ceq", "ceqh": "spu_ceqh", "ceqb": "spu_ceqb",
            "cgt": "spu_cgt", "cgth": "spu_cgth", "cgtb": "spu_cgtb",
            "clgt": "spu_clgt", "clgth": "spu_clgth", "clgtb": "spu_clgtb",
            "mpy": "spu_mpy", "mpyu": "spu_mpyu",
            "mpyh": "spu_mpyh", "mpyhh": "spu_mpyhh", "mpys": "spu_mpys",
            "fa": "spu_fa", "fs": "spu_fs", "fm": "spu_fm",
            "fi": "spu_fi",   # floating interpolate (reciprocal refine)
            "fceq": "spu_fceq", "fcgt": "spu_fcgt",
            "fcmeq": "spu_fcmeq", "fcmgt": "spu_fcmgt",
            # double-precision (2 doubles/reg) + double compares
            "dfa": "spu_dfa", "dfs": "spu_dfs", "dfm": "spu_dfm",
            "dfceq": "spu_dfceq", "dfcmeq": "spu_dfcmeq",
            "dfcgt": "spu_dfcgt", "dfcmgt": "spu_dfcmgt",
            "mpyhhu": "spu_mpyhhu",
            "eqv": "spu_eqv", "absdb": "spu_absdb", "avgb": "spu_avgb",
            "cg": "spu_cg", "bg": "spu_bg",
            "sumb": "spu_sumb",
            # double precision
            "dfa": "spu_dfa", "dfs": "spu_dfs", "dfm": "spu_dfm",
            # Phase 2: register-variable shifts/rotates
            "shl": "spu_shl", "shlh": "spu_shlh",
            "rot": "spu_rot", "roth": "spu_roth",
            "shlqbi": "spu_shlqbi",  "rotqbi": "spu_rotqbi",
            "shlqby": "spu_shlqby",  "rotqby": "spu_rotqby",
            "shlqbybi": "spu_shlqbybi", "rotqbybi": "spu_rotqbybi",
            # Phase 3: rotate-and-mask (register-variable)
            "rotm": "spu_rotm", "rotma": "spu_rotma",
            "rothm": "spu_rothm", "rothma": "spu_rothma",
            "rotqmbi": "spu_rotqmbi", "rotqmby": "spu_rotqmby",
            "rotqmbybi": "spu_rotqmbybi",
            # Phase 3: indexed constant generators (insertion masks)
            "cbx": "spu_cbx", "chx": "spu_chx",
            "cwx": "spu_cwx", "cdx": "spu_cdx",
        }
        if mn in rr_bin:
            return f"{g(rt())} = {rr_bin[mn]}({g(ra())}, {g(rb())});"

        # ---- unary (register) ----
        rr_un = {
            "clz": "spu_clz", "cntb": "spu_cntb",
            "fscrrd": "spu_fscrrd",
            "gb": "spu_gb", "gbh": "spu_gbh", "gbb": "spu_gbb",
            "fesd": "spu_fesd", "frds": "spu_frds",
            "frsqest": "spu_frsqest", "frest": "spu_frest",
            "fesd": "spu_fesd", "frds": "spu_frds",   # single<->double convert
            # Phase 3
            "xsbh": "spu_xsbh", "xshw": "spu_xshw", "xswd": "spu_xswd",
            "orx": "spu_orx",
            "fsm": "spu_fsm", "fsmh": "spu_fsmh", "fsmb": "spu_fsmb",
            "mfspr": "spu_mfspr",
        }
        if mn in rr_un:
            return f"{g(rt())} = {rr_un[mn]}({g(ra())});"

        # ---- move register (or rt,ra,ra) handled by generic 'or' above ----

        # ---- arithmetic / logical / compare immediate ----
        ri_imm = {
            "ai": "spu_ai", "ahi": "spu_ahi", "sfi": "spu_sfi", "sfhi": "spu_sfhi",
            "andi": "spu_andi", "ori": "spu_ori", "xori": "spu_xori",
            "ceqi": "spu_ceqi", "cgti": "spu_cgti", "clgti": "spu_clgti",
            "ceqbi": "spu_ceqbi", "ceqhi": "spu_ceqhi",
            "clgtbi": "spu_clgtbi", "clgthi": "spu_clgthi",
            "cgthi": "spu_cgthi", "cgtbi": "spu_cgtbi",
            "mpyi": "spu_mpyi", "mpyui": "spu_mpyui",
            # Phase 3: halfword/byte immediate logic
            "andhi": "spu_andhi", "andbi": "spu_andbi",
            "orhi":  "spu_orhi",  "orbi":  "spu_orbi",
            "xorhi": "spu_xorhi", "xorbi": "spu_xorbi",
            "dftsv": "spu_dftsv",
            # RI8 float<->int conversions with scale (i8 in ops[2])
            "cflts": "spu_cflts", "cfltu": "spu_cfltu",
            "csflt": "spu_csflt", "cuflt": "spu_cuflt",
        }
        if mn in ri_imm:
            return f"{g(rt())} = {ri_imm[mn]}({g(ra())}, {_imm(ops[2])});"

        # ---- shift / rotate immediate ----
        sh_imm = {
            "shli": "spu_shli", "shlhi": "spu_shlhi",
            "roti": "spu_roti", "rothi": "spu_rothi",
            "rotmi": "spu_rotmi", "rotmai": "spu_rotmai", "rotmhi": "spu_rotmhi",
            "rotmahi": "spu_rotmahi",
            "shlqbyi": "spu_shlqbyi", "rotqbyi": "spu_rotqbyi",
            "shlqbii": "spu_shlqbii", "rotqbii": "spu_rotqbii",
            # Phase 3: rotate-and-mask immediate + d-form constant generators
            "rothmi": "spu_rothmi",
            "rotqmbii": "spu_rotqmbii", "rotqmbyi": "spu_rotqmbyi",
            "cbd": "spu_cbd", "chd": "spu_chd",
            "cwd": "spu_cwd", "cdd": "spu_cdd",
        }
        if mn in sh_imm:
            # Disassembler quirk: the quad shift/rotate RI7 forms (shlqbyi,
            # rotqbyi, shlqbii, rotqbii) are matched against SPU_RR first and
            # therefore emitted with 3-register operands, with the i7 bits
            # disguised as "$rN". The register index IS the immediate value,
            # so we strip the "$r" and use the digits literally.
            tok = ops[2]
            if tok.startswith("$r"):
                tok = tok[2:]
            else:
                tok = _imm(tok)
            return f"{g(rt())} = {sh_imm[mn]}({g(ra())}, {tok});"

        # ---- select / shuffle (RRR: rt, ra, rb, rc) ----
        if mn == "selb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_selb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn == "shufb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_shufb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn in ("fma", "fms", "fnms", "mpya"):
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rc)});"
        # sfx: extended subtract — RT is also a source (carry-in = low bit of old RT).
        if mn == "sfx":
            return f"{g(rt())} = spu_sfx({g(ra())}, {g(rb())}, {g(rt())});"
        # cgx: extended carry-generate — RT is also a source (carry-in = low bit).
        if mn == "cgx":
            return f"{g(rt())} = spu_cgx({g(ra())}, {g(rb())}, {g(rt())});"
        # double FMA (dfma/dfms/dfnms/dfnma): 3-register, RT is the accumulator (c).
        if mn in ("dfma", "dfms", "dfnms", "dfnma"):
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rt())});"
        # mpyhha/mpyhhau: high-half multiply accumulated into RT (3-register).
        if mn in ("mpyhha", "mpyhhau"):
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rt())});"

        # ---- quadword loads / stores ----
        if mn == "lqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"{g(rt())} = spu_ls_read128(ctx, {g(base)}._u32[0] + {disp});"
        if mn == "stqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"spu_ls_write128(ctx, {g(base)}._u32[0] + {disp}, {g(rt())});"
        if mn in ("lqa", "lqr"):
            return f"{g(rt())} = spu_ls_read128(ctx, {_imm(ops[1])});"
        if mn in ("stqa", "stqr"):
            return f"spu_ls_write128(ctx, {_imm(ops[1])}, {g(rt())});"
        if mn == "lqx":
            return f"{g(rt())} = spu_ls_read128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0]);"
        if mn == "stqx":
            return f"spu_ls_write128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0], {g(rt())});"

        # ---- channel ops ----
        if mn == "rdch":
            return f"{g(rt())} = spu_rdch(ctx, {_chan(ops[1])});"
        if mn == "rchcnt":
            # CBEA: the count lands in the PREFERRED word, remaining slots ZERO
            # (splatting it is the spu_link bug class; RPCS3 = v128::from32r).
            return f"{g(rt())} = spu_pref_u32(spu_rchcnt(ctx, {_chan(ops[1])}));"
        if mn == "wrch":
            # operands: channel, $rt
            return f"spu_wrch(ctx, {_chan(ops[0])}, {g(_reg(ops[1]))});"

        # ---- branches ----
        if mn in ("br", "bra"):
            tgt = self._branch_target(insn)
            # SELF-LOOP TRAP: `br .` (target == this instruction) is an infinite
            # hang on real SPU -- a deliberate trap, no forward progress. Emitting
            # `goto loc_self` busy-spins the host thread forever; stop the SPU
            # instead (same halt path the lifter emits for a `stop` instruction).
            if tgt == addr:
                return "ctx->status = SPU_STATUS_STOPPED_BY_HALT; return;"
            return self._uncond_branch(tgt, func)
        if mn in ("brsl", "brasl"):
            # The disassembler drops the link register from brsl operands, so
            # recover it from the raw encoding (rt = bits 25-31 = raw & 0x7F).
            link_rt = insn.raw & 0x7F
            tgt = self._branch_target(insn)
            # Link register: preferred word only, other slots ZERO (real HW /
            # RPCS3 v128::from32r) -- splatting corrupts full-quadword link use.
            link = f"{g(link_rt)} = spu_link(0x{addr + 4:X});"
            # SELF-LOOP TRAP: `brsl rX, .` (target == this instruction) is an
            # infinite loop on real SPU (re-sets the link each pass, never
            # advances) -- a trap, NOT a call. Emitting a host call recurses
            # forever -> host stack overflow -> segfault (observed crashing the
            # boot in cri_audio_00023C58). Set the link, then stop the SPU (same
            # halt path the lifter emits for a `stop` instruction).
            if tgt == addr:
                return f"{link} ctx->status = SPU_STATUS_STOPPED_BY_HALT; return;"
            # PC-GETTER IDIOM: `brsl rX, .+4` (target == next instruction) just
            # loads PC+4 into rX for PC-relative addressing / computed jump tables;
            # it is NOT a real call. Emitting a host call here imbalances the C
            # call/return nesting -- the "callee" falls through into the rest of
            # the function and a later `bi $r0` return unwinds to this brsl's frame
            # instead of the real caller (observed: SPURS taskset LoadElf's return
            # landed back inside its own clear loop, running it with a stale count).
            # Treat it as: set the link, then fall through to addr+4.
            if tgt == addr + 4:
                return f"{link} {self._uncond_branch(addr + 4, func)}"
            if tgt is not None:
                self.call_targets.add(tgt)
                return f"{link} {self.prefix}spu_func_{tgt:08X}(ctx);"
            return f"{link} /* TODO spu: brsl unresolved target */;"
        if mn in _COND_BR:
            tgt = self._branch_target(insn)
            cond = self._cond(mn, _reg(ops[0]))
            if tgt is None:
                return f"/* TODO spu: {mn} {insn.operands} */;"
            if func.start_addr <= tgt < func.end_addr:
                return f"if ({cond}) goto loc_{tgt:08X};"
            self.branch_targets.add(tgt)
            return (f"if ({cond}) {{ ctx->pc = 0x{tgt:X}; "
                    f"{self.prefix}spu_func_{tgt:08X}(ctx); return; }}")
        # For bi/bisl the disassembler emits only "$rA" (ops[0] = target reg).
        if mn in ("bi",):
            tgt_reg = _reg(ops[0])
            # SPU ABI: $r0 is the link register. `bi $r0` is the standard
            # function return — translate to a host return so call/return
            # discipline matches the C function nesting from brsl. EXCEPTION:
            # when r0 was reloaded from memory (lqa/lqr) it is a COMPUTED TAIL
            # JUMP (e.g. the SPURS task launch `lqa $r0,savedContextLr; bi $r0`),
            # flagged by compute_bi_r0_jumps() — emit the indirect dispatch.
            if tgt_reg == "0" and addr not in self.bi_r0_jump:
                return "return;"
            return (f"ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"spu_indirect_branch(ctx); return;")
        # iret: interrupt return -> branch to the saved interrupt PC (SRR0).
        if mn == "iret":
            return ("ctx->pc = ctx->srr0; "
                    "spu_indirect_branch(ctx); return;")
        if mn in ("bisl",):
            link_rt = insn.raw & 0x7F            # link reg dropped from operands
            tgt_reg = _reg(ops[0])
            return (f"{g(link_rt)} = spu_link(0x{addr + 4:X}); "
                    f"ctx->pc = {g(tgt_reg)}._u32[0]; spu_indirect_branch(ctx);")
        # bisled: set link, branch to RA only if an external event is pending.
        if mn in ("bisled",):
            link_rt = insn.raw & 0x7F
            tgt_reg = _reg(ops[0])
            return (f"{g(link_rt)} = spu_splat_u32(0x{addr + 4:X}); "
                    f"if ((ctx->event_status & ctx->event_mask) != 0) {{ "
                    f"ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"spu_indirect_branch(ctx); return; }}")
        # biz/binz/bihz/bihnz: ops[0] = condition reg, ops[1] = target reg.
        if mn in ("biz", "binz", "bihz", "bihnz"):
            cond = self._cond(mn[1:], _reg(ops[0]))   # strip leading 'b' -> iz/inz...
            tgt_reg = _reg(ops[1])
            # $r0 is the link register: a conditional branch to it is a
            # conditional function return — emit a host return so it composes
            # with the brsl->C-call nesting (mirrors the `bi $r0` case above).
            # Dispatching to the return address would miss the C frame and
            # land on an unregistered mid-function PC.
            if tgt_reg == "0" and addr not in self.bi_r0_jump:
                return f"if ({cond}) return;"
            return (f"if ({cond}) {{ ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"spu_indirect_branch(ctx); return; }}")

        # hint-for-branch: pure performance hint, safe to drop
        if mn in ("hbr", "hbra", "hbrr"):
            return "/* branch hint (ignored) */;"
        # mtspr: SPU special-purpose-register writes are ignored (RPCS3: SPRs unused)
        if mn == "mtspr":
            return "/* mtspr: SPR write ignored */;"

        # ---- fallthrough: unsupported ----
        self.unsupported[mn] = self.unsupported.get(mn, 0) + 1
        return f"/* TODO spu: {mn} {insn.operands} */;"

    # ------------------------------------------------------------------ #
    def _cond(self, mn: str, reg: str) -> str:
        """Condition expression on preferred slot for conditional branches."""
        word = f"ctx->gpr[{reg}]._u32[0]"
        half = f"ctx->gpr[{reg}]._u16[1]"   # preferred halfword (lane 1 of word 0)
        table = {
            "brz": f"{word} == 0",      "brnz": f"{word} != 0",
            "brhz": f"{half} == 0",     "brhnz": f"{half} != 0",
            "iz": f"{word} == 0",       "inz": f"{word} != 0",
            "ihz": f"{half} == 0",      "ihnz": f"{half} != 0",
        }
        return table.get(mn, f"{word} != 0")

    def _uncond_branch(self, tgt, func: LiftedFunction) -> str:
        if tgt is None:
            return "/* TODO spu: unresolved branch */;"
        if func.start_addr <= tgt < func.end_addr:
            return f"goto loc_{tgt:08X};"
        self.branch_targets.add(tgt)
        return f"{{ ctx->pc = 0x{tgt:X}; {self.prefix}spu_func_{tgt:08X}(ctx); return; }}"

    # ------------------------------------------------------------------ #
    def emit_header(self) -> str:
        lines = [HEADER_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx);")
        defined = {f.start_addr for f in self.functions}
        for t in sorted(self.call_targets | self.branch_targets):
            if t not in defined:
                lines.append(f"void {self.prefix}spu_func_{t:08X}(spu_context* ctx); /* external */")
        lines.append("")
        lines.append("/* Runtime glue (runtime/spu/spu_channels.c) */")
        lines.append("void spu_register_function(uint32_t addr, void (*fn)(spu_context*));")
        lines.append("/* Call once at init to register this image's functions for")
        lines.append(" * indirect-branch dispatch (spu_indirect_branch). */")
        lines.append(f"void {self.prefix}spu_recomp_register(void);")
        lines.append("")
        return "\n".join(lines)

    def emit_source(self) -> str:
        lines = [SOURCE_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx) {{")
            for b in f.body_lines:
                lines.append(b if b.endswith(":") else f"    {b}")
            lines.append("}")
            lines.append("")

        # Stubs for cross-function branch/call targets the function-boundary
        # detector did not promote to standalone functions. The lifter emits
        # `spu_func_<tgt>(ctx)` calls eagerly, so the linker needs a symbol;
        # at runtime we route through spu_indirect_branch which either lands
        # on a registered mid-function entry (if one was emitted) or halts
        # cleanly with a "PC X not registered" diagnostic.
        defined = {f.start_addr for f in self.functions}
        externs = sorted((self.call_targets | self.branch_targets) - defined)
        if externs:
            lines.append("/* Indirect-dispatch stubs for cross-function targets the")
            lines.append(" * function detector did not seed (typically conditional")
            lines.append(" * branches that escape a function's range). */")
            for t in externs:
                lines.append(f"void {self.prefix}spu_func_{t:08X}(spu_context* ctx) {{")
                lines.append(f"    ctx->pc = 0x{t:X}u; spu_indirect_branch(ctx);")
                lines.append("}")
            lines.append("")

        lines.append("/* Function table */")
        lines.append("typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;")
        lines.append("static const spu_func_entry spu_function_table[] = {")
        for f in self.functions:
            lines.append(f'    {{ 0x{f.start_addr:08X}u, {f.name}, "{f.name}" }},')
        lines.append("    { 0, NULL, NULL }")
        lines.append("};")
        lines.append("")
        lines.append(f"void {self.prefix}spu_recomp_register(void) {{")
        lines.append("    for (const spu_func_entry* e = spu_function_table; e->func; ++e)")
        lines.append("        spu_register_function(e->addr, e->func);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description="SPU to C lifter for ps3recomp")
    p.add_argument("input", nargs="?", default=None,
                   help="Raw SPU binary (local-store image) or segment. "
                        "Omit if --auto-functions is set.")
    p.add_argument("--output", "-o", default=".", help="Output directory")
    p.add_argument("--header-name", default="spu_recomp.h")
    p.add_argument("--source-name", default="spu_recomp.c")
    p.add_argument("--base", type=lambda x: int(x, 0), default=0,
                   help="Base local-store address")
    p.add_argument("--offset", type=lambda x: int(x, 0), default=0)
    p.add_argument("--length", type=lambda x: int(x, 0), default=0)
    p.add_argument("--functions", metavar="FILE",
                   help="JSON list [{\"start\":addr,\"end\":addr}, ...]")
    p.add_argument("--auto-functions", metavar="ELF",
                   help="Auto-detect function boundaries from the given SPU "
                        "ELF using find_spu_functions.py (entry + brsl/brasl "
                        "targets + STT_FUNC symbols). When set, .text is "
                        "read from this ELF and the positional <input> arg "
                        "is ignored.")
    p.add_argument("--trace", action="store_true",
                   help="Emit spu_trace_pc/spu_trace_rt around each instruction "
                        "for §3 diff-vs-RPCS3 validation. Output goes to stderr "
                        "unless spu_trace_init(path) is called by the harness.")
    p.add_argument("--symbol-prefix", default="",
                   help="Prefix for all emitted spu_func_* / spu_recomp_register "
                        "symbols, so multiple lifted SPU images can link into one "
                        "binary without colliding (e.g. flow_spu_00_). Default: none.")
    p.add_argument("--extra-funcs", default="",
                   help="Comma-separated extra function entry addresses (e.g. "
                        "0x10F8,0x808) to add as boundaries -- for indirect-branch "
                        "targets that --auto-functions can't detect statically. "
                        "Splits the containing auto-detected function at each addr.")
    args = p.parse_args()

    if args.auto_functions:
        from find_spu_functions import detect_functions, parse_elf, pick_text
        with open(args.auto_functions, "rb") as f:
            elf_buf = f.read()
        funcs, (text_off, base, size) = detect_functions(elf_buf)
        data = elf_buf[text_off:text_off + size]
        if args.base != 0:
            base = args.base  # caller override
        bounds = funcs
    else:
        with open(args.input, "rb") as f:
            data = f.read()
        data = data[args.offset:]
        if args.length:
            data = data[:args.length]
        base = args.base

        if args.functions:
            with open(args.functions) as f:
                flist = json.load(f)
            bounds = [(int(str(e["start"]), 0), int(str(e["end"]), 0))
                      for e in flist]
        else:
            # No boundary info: treat the whole image as one function.
            bounds = [(base, base + len(data))]

    # Add extra function entry points (indirect-branch targets auto-detect misses)
    # by splitting whichever bound contains each address.
    if args.extra_funcs:
        extra = [int(x, 0) for x in args.extra_funcs.split(",") if x.strip()]
        bset = sorted(set(bounds))
        for a in extra:
            newb = []
            split = False
            for (s, e) in bset:
                if s < a < e:
                    newb.append((s, a)); newb.append((a, e)); split = True
                else:
                    newb.append((s, e))
            if not split and not any(s == a for s, _ in bset):
                newb.append((a, base + len(data)))
            bset = sorted(set(newb))
        bounds = bset
        sys.stderr.write("[spu_lifter] added extra funcs: %s\n" %
                         ", ".join("0x%X" % a for a in extra))

    insns = disassemble_spu(data, base)

    lifter = SPULifter(trace=args.trace, prefix=args.symbol_prefix)
    lifter.bi_r0_jump = compute_bi_r0_jumps(insns, bounds)
    if lifter.bi_r0_jump:
        print(f"  {len(lifter.bi_r0_jump)} `bi $r0` computed-jump site(s) "
              f"(r0 reloaded via lqa/lqr): "
              f"{', '.join(f'0x{a:X}' for a in sorted(lifter.bi_r0_jump))}")
    lifter.func_starts = {s for s, e in bounds}  # for fall-through tail-call chaining
    for s, e in bounds:
        lifter.lift_function(insns, s, e)

    os.makedirs(args.output, exist_ok=True)
    hp = os.path.join(args.output, args.header_name)
    sp = os.path.join(args.output, args.source_name)
    with open(hp, "w") as f:
        f.write(lifter.emit_header())
    with open(sp, "w") as f:
        f.write(lifter.emit_source())

    print(f"Wrote {hp}")
    print(f"Wrote {sp}")
    print(f"  {len(lifter.functions)} function(s) lifted")
    print(f"  {len(lifter.call_targets)} call target(s)")
    if lifter.unsupported:
        total = sum(lifter.unsupported.values())
        print(f"  {total} unsupported instruction(s) across "
              f"{len(lifter.unsupported)} mnemonic(s):")
        for mn, n in sorted(lifter.unsupported.items(), key=lambda kv: -kv[1]):
            print(f"      {mn:<10s} {n}")


if __name__ == "__main__":
    main()
