/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000290(spu_context* ctx) {
        ctx->gpr[30] = spu_ceqi(ctx->gpr[3], 0);
        ctx->gpr[10] = spu_ls_read128(ctx, 0x1D0);
        ctx->gpr[8] = spu_ila(0x8000);
        ctx->gpr[22] = spu_rotqbyi(ctx->gpr[3], 0);
        ctx->gpr[29] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[52] = spu_cwd(ctx->gpr[1], 4);
        ctx->gpr[4] = spu_ceqi(ctx->gpr[3], 1);
        ctx->gpr[40] = spu_ls_read128(ctx, 0x850);
        ctx->gpr[51] = spu_ori(ctx->gpr[8], 0);
        ctx->gpr[41] = spu_ls_read128(ctx, 0x860);
        ctx->gpr[33] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[27] = spu_fsmbi(0x0);
        ctx->gpr[35] = spu_il(128);
        ctx->gpr[20] = spu_rotqby(ctx->gpr[10], ctx->gpr[12]);
        ctx->gpr[46] = spu_il(208);
        ctx->gpr[38] = spu_fsmbi(0x0);
        ctx->gpr[47] = spu_il(1);
        ctx->gpr[48] = spu_ilh(0x7F7F);
        ctx->gpr[7] = spu_ceqi(ctx->gpr[20], 32);
        ctx->gpr[9] = spu_sfi(ctx->gpr[20], 0);
        ctx->gpr[5] = spu_sfi(ctx->gpr[7], 0);
        ctx->gpr[6] = spu_shlh(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[3] = spu_or(ctx->gpr[29], ctx->gpr[5]);
        ctx->gpr[49] = spu_ilh(0x4040);
        ctx->gpr[2] = spu_ceqbi(ctx->gpr[3], 0);
        ctx->gpr[32] = spu_fsmb(ctx->gpr[6]);
        ctx->gpr[31] = spu_fscrrd(ctx->gpr[2]);
        ctx->gpr[45] = spu_ilh(0x808);
        ctx->gpr[50] = spu_ilh(0x3C3C);
        ctx->gpr[42] = spu_ilh(0x303);
        ctx->gpr[43] = spu_ilh(0x202);
        ctx->gpr[34] = spu_ilh(0x808);
        ctx->gpr[44] = spu_ila(0x10001);
        ctx->gpr[37] = spu_ilh(0xFF);
        ctx->gpr[39] = spu_il(1);
        ctx->gpr[36] = spu_il(180);
        ctx->gpr[28] = spu_ila(0x100);
}

void spu_func_00000324(spu_context* ctx) {
        ctx->gpr[57] = spu_ls_read128(ctx, 0x1C0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[28]);
        ctx->gpr[55] = spu_rotqbyi(ctx->gpr[57], 4);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[57]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[55]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[35]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[27]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[46]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdAtomicStat);
        /* sync */;
        ctx->gpr[54] = spu_ls_read128(ctx, 0x1C0);
        ctx->gpr[18] = spu_ls_read128(ctx, 0x170);
        ctx->gpr[25] = spu_ls_read128(ctx, 0x130);
        ctx->gpr[24] = spu_ceqi(ctx->gpr[22], 0);
        ctx->gpr[26] = spu_ls_read128(ctx, 0x190);
        ctx->gpr[19] = spu_ls_read128(ctx, 0x120);
        ctx->gpr[23] = spu_ls_read128(ctx, 0x180);
        ctx->gpr[53] = spu_rotqby(ctx->gpr[54], ctx->gpr[8]);
        ctx->gpr[6] = spu_rotqby(ctx->gpr[18], ctx->gpr[15]);
        ctx->gpr[11] = spu_fsm(ctx->gpr[24]);
        ctx->gpr[21] = spu_sf(ctx->gpr[26], ctx->gpr[25]);
        ctx->gpr[16] = spu_shlqbi(ctx->gpr[47], ctx->gpr[53]);
        ctx->gpr[14] = spu_sf(ctx->gpr[23], ctx->gpr[19]);
        ctx->gpr[17] = spu_orc(ctx->gpr[21], ctx->gpr[32]);
        ctx->gpr[15] = spu_andi(ctx->gpr[6], 255);
        ctx->gpr[13] = spu_a(ctx->gpr[14], ctx->gpr[17]);
        ctx->gpr[25] = spu_rotqbyi(ctx->gpr[14], 0);
        ctx->gpr[4] = spu_and(ctx->gpr[15], ctx->gpr[16]);
        ctx->gpr[11] = spu_shufb(ctx->gpr[13], ctx->gpr[14], ctx->gpr[18]);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = 0x594; spu_func_00000594(ctx); return; }
        ctx->gpr[16] = spu_ls_read128(ctx, 0x170);
        ctx->gpr[12] = spu_il(0);
        ctx->gpr[8] = spu_ls_read128(ctx, 0x160);
        ctx->gpr[58] = spu_clgtbi(ctx->gpr[18], 0);
        ctx->gpr[6] = spu_ls_read128(ctx, 0x1D0);
        ctx->gpr[9] = spu_sf(ctx->gpr[18], ctx->gpr[45]);
        ctx->gpr[15] = spu_ls_read128(ctx, 0x100);
        ctx->gpr[66] = spu_ls_read128(ctx, 0x1E0);
        ctx->gpr[75] = spu_ls_read128(ctx, 0x110);
        ctx->gpr[23] = spu_rotqby(ctx->gpr[16], ctx->gpr[4]);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[8], ctx->gpr[12]);
        ctx->gpr[72] = spu_rotqby(ctx->gpr[6], ctx->gpr[12]);
        ctx->gpr[65] = spu_clgtbi(ctx->gpr[15], 8);
        ctx->gpr[2] = spu_andi(ctx->gpr[23], 255);
        ctx->gpr[68] = spu_rotqby(ctx->gpr[66], ctx->gpr[12]);
        ctx->gpr[78] = spu_ceqi(ctx->gpr[3], 0);
        ctx->gpr[19] = spu_rotqby(ctx->gpr[16], ctx->gpr[14]);
        ctx->gpr[5] = spu_sfi(ctx->gpr[2], 0);
        ctx->gpr[61] = spu_ls_read128(ctx, 0x140);
        ctx->gpr[65] = spu_shufb(ctx->gpr[15], ctx->gpr[34], ctx->gpr[69]);
        ctx->gpr[14] = spu_rotqby(ctx->gpr[6], ctx->gpr[8]);
        ctx->gpr[79] = spu_shlh(ctx->gpr[51], ctx->gpr[5]);
        ctx->gpr[17] = spu_ls_read128(ctx, 0x150);
        ctx->gpr[76] = spu_clgtbi(ctx->gpr[75], 8);
        ctx->gpr[67] = spu_rotqbyi(ctx->gpr[66], 0);
        ctx->gpr[71] = spu_sfi(ctx->gpr[72], 0);
        ctx->gpr[66] = spu_fsmb(ctx->gpr[19]);
        ctx->gpr[76] = spu_shufb(ctx->gpr[75], ctx->gpr[34], ctx->gpr[74]);
        ctx->gpr[73] = spu_ls_read128(ctx, 0x1A0);
        ctx->gpr[78] = spu_shufb(ctx->gpr[12], ctx->gpr[79], ctx->gpr[26]);
        ctx->gpr[16] = spu_ls_read128(ctx, 0x220);
        ctx->gpr[64] = spu_a(ctx->gpr[69], ctx->gpr[74]);
        ctx->gpr[42] = spu_selb(ctx->gpr[14], ctx->gpr[14], ctx->gpr[10]);
        ctx->gpr[62] = spu_nand(ctx->gpr[68], ctx->gpr[68]);
        ctx->gpr[65] = spu_fsmb(ctx->gpr[26]);
        ctx->gpr[26] = spu_ila(0x8000);
        ctx->gpr[13] = spu_rotqbii(ctx->gpr[9], 2);
        ctx->gpr[57] = spu_clgtb(ctx->gpr[64], ctx->gpr[18]);
        ctx->gpr[24] = spu_rotqby(ctx->gpr[8], ctx->gpr[12]);
        ctx->gpr[63] = spu_shlh(ctx->gpr[26], ctx->gpr[71]);
        ctx->gpr[14] = spu_fsmbi(0x1000);
        ctx->gpr[59] = spu_clgtb(ctx->gpr[61], ctx->gpr[18]);
        /* branch hint (ignored) */;
        ctx->gpr[60] = spu_roth(ctx->gpr[62], ctx->gpr[112]);
        ctx->gpr[69] = spu_cbd(ctx->gpr[1], 11);
        ctx->gpr[75] = spu_or(ctx->gpr[66], ctx->gpr[65]);
        ctx->gpr[55] = spu_fsmb(ctx->gpr[63]);
        ctx->gpr[56] = spu_and(ctx->gpr[58], ctx->gpr[59]);
        ctx->gpr[53] = spu_ceqbi(ctx->gpr[15], 0);
        ctx->gpr[54] = spu_xori(ctx->gpr[57], -1);
        ctx->gpr[78] = spu_fsmb(ctx->gpr[60]);
        ctx->gpr[49] = spu_shufb(ctx->gpr[55], ctx->gpr[56], ctx->gpr[4]);
        ctx->gpr[8] = spu_or(ctx->gpr[53], ctx->gpr[54]);
        ctx->gpr[2] = spu_clgtb(ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[7] = spu_ceqbi(ctx->gpr[75], 0);
        ctx->gpr[60] = spu_clgtb(ctx->gpr[15], ctx->gpr[18]);
        ctx->gpr[50] = spu_shufb(ctx->gpr[4], ctx->gpr[13], ctx->gpr[5]);
        ctx->gpr[3] = spu_ceqb(ctx->gpr[16], ctx->gpr[10]);
        ctx->gpr[77] = spu_and(ctx->gpr[7], ctx->gpr[8]);
        ctx->gpr[79] = spu_ceqbi(ctx->gpr[73], 0);
        ctx->gpr[76] = spu_xori(ctx->gpr[2], -1);
        ctx->gpr[43] = spu_shufb(ctx->gpr[5], ctx->gpr[3], ctx->gpr[71]);
        ctx->gpr[74] = spu_or(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[72] = spu_or(ctx->gpr[75], ctx->gpr[60]);
        ctx->gpr[6] = spu_or(ctx->gpr[78], ctx->gpr[79]);
        ctx->gpr[48] = spu_shufb(ctx->gpr[72], ctx->gpr[73], ctx->gpr[70]);
        ctx->gpr[8] = spu_nand(ctx->gpr[6], ctx->gpr[74]);
        ctx->gpr[68] = spu_orhi(ctx->gpr[71], 257);
        ctx->gpr[63] = spu_and(ctx->gpr[70], ctx->gpr[8]);
        ctx->gpr[64] = spu_and(ctx->gpr[68], ctx->gpr[8]);
        ctx->gpr[61] = spu_andbi(ctx->gpr[66], 2);
        ctx->gpr[62] = spu_andbi(ctx->gpr[65], 4);
        ctx->gpr[41] = spu_selb(ctx->gpr[63], ctx->gpr[64], ctx->gpr[15]);
        ctx->gpr[9] = spu_andhi(ctx->gpr[60], 257);
        ctx->gpr[40] = spu_selb(ctx->gpr[63], ctx->gpr[64], ctx->gpr[10]);
        ctx->gpr[58] = spu_or(ctx->gpr[61], ctx->gpr[62]);
        ctx->gpr[66] = spu_andbi(ctx->gpr[14], 32);
        ctx->gpr[76] = spu_or(ctx->gpr[9], ctx->gpr[58]);
        ctx->gpr[59] = spu_clgth(ctx->gpr[15], ctx->gpr[10]);
        ctx->gpr[59] = spu_shufb(ctx->gpr[10], ctx->gpr[15], ctx->gpr[55]);
        ctx->gpr[57] = spu_rotqby(ctx->gpr[55], ctx->gpr[8]);
        ctx->gpr[56] = spu_clgth(ctx->gpr[57], ctx->gpr[55]);
        ctx->gpr[56] = spu_shufb(ctx->gpr[55], ctx->gpr[57], ctx->gpr[18]);
        ctx->gpr[54] = spu_rotqby(ctx->gpr[18], ctx->gpr[4]);
        ctx->gpr[53] = spu_clgth(ctx->gpr[54], ctx->gpr[18]);
        ctx->gpr[53] = spu_shufb(ctx->gpr[18], ctx->gpr[54], ctx->gpr[16]);
        ctx->gpr[17] = spu_rotqby(ctx->gpr[16], ctx->gpr[2]);
        ctx->gpr[13] = spu_clgth(ctx->gpr[17], ctx->gpr[16]);
        ctx->gpr[13] = spu_shufb(ctx->gpr[16], ctx->gpr[17], ctx->gpr[12]);
        ctx->gpr[44] = spu_selb(ctx->gpr[12], ctx->gpr[12], ctx->gpr[11]);
        ctx->gpr[7] = spu_ceqh(ctx->gpr[15], ctx->gpr[11]);
        ctx->gpr[4] = spu_ceqh(ctx->gpr[10], ctx->gpr[11]);
        ctx->gpr[37] = spu_shufb(ctx->gpr[4], ctx->gpr[7], ctx->gpr[5]);
        ctx->gpr[3] = spu_and(ctx->gpr[8], ctx->gpr[5]);
        ctx->gpr[2] = spu_gbh(ctx->gpr[3]);
        ctx->gpr[79] = spu_shli(ctx->gpr[2], 16);
        ctx->gpr[79] = spu_iohl(ctx->gpr[79], 0x8000);
        ctx->gpr[74] = spu_clz(ctx->gpr[79]);
        ctx->gpr[77] = spu_ai(ctx->gpr[74], -3);
        ctx->gpr[75] = spu_rotqbybi(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[73] = spu_andi(ctx->gpr[75], 255);
        ctx->gpr[52] = spu_selb(ctx->gpr[73], ctx->gpr[74], ctx->gpr[64]);
        ctx->gpr[71] = spu_ceqi(ctx->gpr[64], 16);
        ctx->gpr[70] = spu_ceqi(ctx->gpr[71], 0);
        ctx->gpr[68] = spu_sfi(ctx->gpr[71], 0);
        ctx->gpr[65] = spu_fsm(ctx->gpr[70]);
        ctx->gpr[69] = spu_selb(ctx->gpr[68], ctx->gpr[67], ctx->gpr[63]);
        ctx->gpr[65] = spu_shufb(ctx->gpr[66], ctx->gpr[64], ctx->gpr[12]);
        spu_ls_write128(ctx, 0x1E0, ctx->gpr[63]);
        ctx->gpr[62] = spu_ceq(ctx->gpr[20], ctx->gpr[12]);
        ctx->gpr[7] = spu_rotqbyi(ctx->gpr[12], 0);
        ctx->gpr[61] = spu_sfi(ctx->gpr[62], 0);
        ctx->gpr[60] = spu_or(ctx->gpr[29], ctx->gpr[61]);
        ctx->gpr[59] = spu_ceqbi(ctx->gpr[60], 0);
        ctx->gpr[58] = spu_fscrrd(ctx->gpr[59]);
        if (ctx->gpr[58]._u16[1] != 0) { ctx->pc = 0x690; spu_func_00000690(ctx); return; }
        ctx->gpr[4] = spu_sfi(ctx->gpr[12], 0);
        ctx->gpr[10] = spu_andi(ctx->gpr[23], 255);
        ctx->gpr[18] = spu_ls_read128(ctx, 0x170);
        ctx->gpr[13] = spu_shlh(ctx->gpr[26], ctx->gpr[4]);
        ctx->gpr[15] = spu_chd(ctx->gpr[1], 0);
        ctx->gpr[4] = spu_ceq(ctx->gpr[12], ctx->gpr[10]);
        ctx->gpr[73] = spu_orc(ctx->gpr[19], ctx->gpr[13]);
        ctx->gpr[15] = spu_selb(ctx->gpr[73], ctx->gpr[18], ctx->gpr[67]);
        spu_ls_write128(ctx, 0x170, ctx->gpr[67]);
        { ctx->pc = 0x5D8; spu_func_000005D8(ctx); return; }
}

void spu_func_00000594(spu_context* ctx) {
        /* branch hint (ignored) */;
        ctx->gpr[7] = spu_il(32);
        ctx->gpr[53] = spu_ls_read128(ctx, 0x1E0);
        ctx->gpr[54] = spu_cbd(ctx->gpr[1], 11);
        ctx->gpr[55] = spu_fsmbi(0x1000);
        ctx->gpr[12] = spu_andbi(ctx->gpr[55], 32);
        ctx->gpr[54] = spu_selb(ctx->gpr[38], ctx->gpr[53], ctx->gpr[17]);
        spu_ls_write128(ctx, 0x1E0, ctx->gpr[17]);
        if (ctx->gpr[31]._u16[1] != 0) { ctx->pc = 0x5FC; spu_func_000005FC(ctx); return; }
        ctx->gpr[9] = spu_orc(ctx->gpr[6], ctx->gpr[4]);
        ctx->gpr[57] = spu_ls_read128(ctx, 0x170);
        ctx->gpr[58] = spu_cbd(ctx->gpr[1], 2);
        ctx->gpr[59] = spu_fsmbi(0x1000);
        ctx->gpr[12] = spu_andbi(ctx->gpr[59], 32);
        ctx->gpr[58] = spu_selb(ctx->gpr[9], ctx->gpr[57], ctx->gpr[56]);
        spu_ls_write128(ctx, 0x170, ctx->gpr[56]);
        { ctx->pc = 0x5FC; spu_func_000005FC(ctx); return; }
}

void spu_func_000005D8(spu_context* ctx) {
        ctx->gpr[64] = spu_or(ctx->gpr[24], ctx->gpr[4]);
        ctx->gpr[63] = spu_ls_read128(ctx, 0x160);
        ctx->gpr[60] = spu_ceqi(ctx->gpr[7], 32);
        ctx->gpr[68] = spu_cwd(ctx->gpr[1], 12);
        ctx->gpr[62] = spu_cbx(ctx->gpr[1], ctx->gpr[7]);
        ctx->gpr[68] = spu_selb(ctx->gpr[64], ctx->gpr[63], ctx->gpr[61]);
        ctx->gpr[62] = spu_selb(ctx->gpr[39], ctx->gpr[27], ctx->gpr[8]);
        spu_ls_write128(ctx, 0x160, ctx->gpr[61]);
        if (ctx->gpr[60]._u32[0] == 0) { ctx->pc = 0x600; spu_func_00000600(ctx); return; }
}

void spu_func_000005FC(spu_context* ctx) {
        ctx->gpr[8] = spu_il(0);
}

void spu_func_00000600(spu_context* ctx) {
        ctx->gpr[78] = spu_ceq(ctx->gpr[7], ctx->gpr[20]);
        ctx->gpr[65] = spu_ls_read128(ctx, 0x120);
        ctx->gpr[10] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[77] = spu_nand(ctx->gpr[78], ctx->gpr[78]);
        ctx->gpr[76] = spu_ceqi(ctx->gpr[10], 0);
        ctx->gpr[75] = spu_sfi(ctx->gpr[77], 0);
        ctx->gpr[26] = spu_a(ctx->gpr[25], ctx->gpr[8]);
        ctx->gpr[9] = spu_fsm(ctx->gpr[76]);
        ctx->gpr[14] = spu_and(ctx->gpr[33], ctx->gpr[75]);
        ctx->gpr[72] = spu_a(ctx->gpr[21], ctx->gpr[8]);
        ctx->gpr[74] = spu_ceqi(ctx->gpr[14], 0);
        ctx->gpr[9] = spu_shufb(ctx->gpr[26], ctx->gpr[65], ctx->gpr[69]);
        ctx->gpr[6] = spu_fsm(ctx->gpr[74]);
        spu_ls_write128(ctx, 0x120, ctx->gpr[69]);
        ctx->gpr[6] = spu_shufb(ctx->gpr[72], ctx->gpr[21], ctx->gpr[71]);
        spu_ls_write128(ctx, 0x130, ctx->gpr[71]);
        /* sync */;
        ctx->gpr[70] = spu_ls_read128(ctx, 0x1C0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[28]);
        ctx->gpr[25] = spu_rotqbyi(ctx->gpr[70], 4);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[70]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[25]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[35]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[27]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[36]);
        ctx->gpr[21] = spu_rdch(ctx, MFC_RdAtomicStat);
        if (ctx->gpr[21]._u32[0] != 0) { ctx->pc = 0x324; spu_func_00000324(ctx); return; }
        ctx->gpr[27] = spu_ls_read128(ctx, 0x180);
        ctx->gpr[30] = spu_il(0);
        ctx->gpr[6] = spu_shufb(ctx->gpr[8], ctx->gpr[30], ctx->gpr[29]);
        spu_ls_write128(ctx, 0x190, ctx->gpr[29]);
        ctx->gpr[9] = spu_shufb(ctx->gpr[8], ctx->gpr[27], ctx->gpr[22]);
        spu_ls_write128(ctx, 0x180, ctx->gpr[22]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x6A8; spu_func_000006A8(ctx); return; }
        ctx->gpr[7] = spu_ori(ctx->gpr[20], 0);
        { ctx->pc = 0x6A8; spu_func_000006A8(ctx); return; }
}

void spu_func_00000690(spu_context* ctx) {
        ctx->gpr[4] = spu_il(0);
        ctx->gpr[11] = spu_ls_read128(ctx, 0x170);
        ctx->gpr[66] = spu_chd(ctx->gpr[1], 0);
        ctx->gpr[66] = spu_selb(ctx->gpr[19], ctx->gpr[11], ctx->gpr[79]);
        spu_ls_write128(ctx, 0x170, ctx->gpr[79]);
        { ctx->pc = 0x5D8; spu_func_000005D8(ctx); return; }
}

void spu_func_000006A8(spu_context* ctx) {
        ctx->gpr[3] = spu_ori(ctx->gpr[12], 0);
        ctx->gpr[32] = spu_ls_read128(ctx, 0x1D0);
        ctx->gpr[33] = spu_cwd(ctx->gpr[1], 12);
        ctx->gpr[33] = spu_selb(ctx->gpr[7], ctx->gpr[32], ctx->gpr[31]);
        spu_ls_write128(ctx, 0x1D0, ctx->gpr[31]);
        return;
}

void spu_func_000006C0(spu_context* ctx) {
        ctx->gpr[23] = spu_shli(ctx->gpr[3], 5);
        ctx->gpr[27] = spu_fsmbi(0x202);
        ctx->gpr[25] = spu_clgti(ctx->gpr[3], 15);
        ctx->gpr[17] = spu_ls_read128(ctx, 0x1C0);
        ctx->gpr[24] = spu_il(2816);
        ctx->gpr[19] = spu_ls_read128(ctx, 0x870);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[10] = spu_fsmbi(0x0);
        ctx->gpr[21] = spu_a(ctx->gpr[23], ctx->gpr[24]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[9] = spu_andbi(ctx->gpr[27], 13);
        ctx->gpr[8] = spu_fsm(ctx->gpr[22]);
        ctx->gpr[26] = spu_ila(0x3FFE0);
        ctx->gpr[7] = spu_rotqmbyi(ctx->gpr[21], 124);
        ctx->gpr[12] = spu_il(32);
        spu_ls_write128(ctx, 0x3FF40, ctx->gpr[10]);
        ctx->gpr[20] = spu_ila(0x3FFD0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[26]);
        ctx->gpr[10] = spu_il(31);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[1]);
        ctx->gpr[8] = spu_shufb(ctx->gpr[9], ctx->gpr[7], ctx->gpr[16]);
        spu_ls_write128(ctx, 0x3FEC0, ctx->gpr[20]);
        ctx->gpr[9] = spu_il(64);
        ctx->gpr[11] = spu_rotqby(ctx->gpr[3], ctx->gpr[4]);
        ctx->gpr[18] = spu_cg(ctx->gpr[16], ctx->gpr[17]);
        ctx->gpr[8] = spu_ilhu(0x8000);
        ctx->gpr[7] = spu_il(2);
        ctx->gpr[19] = spu_selb(ctx->gpr[18], ctx->gpr[18], ctx->gpr[15]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -32);
        ctx->gpr[1] = spu_ila(0x3FFB0);
        ctx->gpr[15] = spu_addx(ctx->gpr[16], ctx->gpr[17], ctx->gpr[15]);
        ctx->gpr[13] = spu_rotqbyi(ctx->gpr[15], 4);
        ctx->gpr[14] = spu_ori(ctx->gpr[15], 0);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[14]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[13]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[12]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[10]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[9]);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[8]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[7]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[4] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[6] = spu_ls_read128(ctx, 0x1D0);
        ctx->gpr[5] = spu_ceq(ctx->gpr[6], ctx->gpr[4]);
        ctx->gpr[3] = spu_gb(ctx->gpr[5]);
        ctx->gpr[2] = spu_cgti(ctx->gpr[3], 11);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x7D8; spu_func_000007D8(ctx); return; }
        ctx->gpr[37] = spu_ls_read128(ctx, 0x3FFC0);
        ctx->gpr[40] = spu_il(2560);
        ctx->gpr[38] = spu_rotqbyi(ctx->gpr[4], 4);
        ctx->gpr[34] = spu_cwd(ctx->gpr[1], 8);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[40]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[4]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[38]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[37]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[10]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[9]);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[8]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[7]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[31] = spu_cdd(ctx->gpr[1], 0);
        ctx->gpr[36] = spu_ls_read128(ctx, 0x3FFC0);
        ctx->gpr[32] = spu_ls_read128(ctx, 0x1D0);
        ctx->gpr[29] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[35] = spu_rotqby(ctx->gpr[36], ctx->gpr[1]);
        ctx->gpr[33] = spu_andi(ctx->gpr[35], 255);
        ctx->gpr[34] = spu_selb(ctx->gpr[33], ctx->gpr[32], ctx->gpr[30]);
        ctx->gpr[31] = spu_selb(ctx->gpr[29], ctx->gpr[30], ctx->gpr[28]);
        spu_ls_write128(ctx, 0x1D0, ctx->gpr[28]);
        /* sync */;
}

void spu_func_000007D8(spu_context* ctx) {
        ctx->gpr[44] = spu_il(0);
        ctx->gpr[43] = spu_ls_read128(ctx, 0x1E0);
        ctx->gpr[45] = spu_chd(ctx->gpr[1], 8);
        ctx->gpr[45] = spu_selb(ctx->gpr[44], ctx->gpr[43], ctx->gpr[42]);
        spu_ls_write128(ctx, 0x1E0, ctx->gpr[42]);
        ctx->gpr[41] = spu_ls_read128(ctx, 0x3FF80);
        ctx->gpr[5] = spu_ori(ctx->gpr[11], 0);
        ctx->gpr[3] = spu_ila(0x100);
        ctx->gpr[11] = spu_il(2560);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[41], ctx->gpr[8]);
        ctx->gpr[0] = spu_splat_u32(0x804); ctx->pc = ctx->gpr[11]._u32[0]; spu_indirect_branch(ctx);
        /* nop */;
        ctx->gpr[1] = spu_ila(0x3FFD0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[0] = spu_splat_u32(0x814); spu_func_00000290(ctx);
        ctx->gpr[0] = spu_splat_u32(0x818); spu_func_000006C0(ctx);
}

void spu_func_00000818(spu_context* ctx) {
        ctx->gpr[1] = spu_ila(0x3FFD0);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_ls_read128(ctx, 0x1C0);
        ctx->gpr[5] = spu_cdd(ctx->gpr[1], 0);
        ctx->gpr[6] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[5] = spu_selb(ctx->gpr[4], ctx->gpr[8], ctx->gpr[7]);
        ctx->gpr[6] = spu_selb(ctx->gpr[3], ctx->gpr[7], ctx->gpr[2]);
        ctx->gpr[3] = spu_fsmbi(0x1000);
        spu_ls_write128(ctx, 0x1C0, ctx->gpr[2]);
        ctx->gpr[3] = spu_andbi(ctx->gpr[3], 32);
        ctx->gpr[0] = spu_splat_u32(0x844); spu_func_000006C0(ctx);
        /* nop */;
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000290u, spu_func_00000290, "spu_func_00000290" },
    { 0x00000324u, spu_func_00000324, "spu_func_00000324" },
    { 0x00000594u, spu_func_00000594, "spu_func_00000594" },
    { 0x000005D8u, spu_func_000005D8, "spu_func_000005D8" },
    { 0x000005FCu, spu_func_000005FC, "spu_func_000005FC" },
    { 0x00000600u, spu_func_00000600, "spu_func_00000600" },
    { 0x00000690u, spu_func_00000690, "spu_func_00000690" },
    { 0x000006A8u, spu_func_000006A8, "spu_func_000006A8" },
    { 0x000006C0u, spu_func_000006C0, "spu_func_000006C0" },
    { 0x000007D8u, spu_func_000007D8, "spu_func_000007D8" },
    { 0x00000818u, spu_func_00000818, "spu_func_00000818" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
